"""Sentence bank for the grammar generator, part A: linked clauses and appositives.

Every sentence here is original. People and organizations are invented unless
the fact is common knowledge. gen_grammar.py turns each entry into questions.
"""

# (independent clause A, independent clause B, how B relates to A)
# B starts lowercase unless its first word is a proper noun.
#   contrast: B pushes against A        result: B happens because of A
#   addition: B adds a parallel point   example: B is one instance of A's claim
CLAUSES = [
    # ---- contrast ----
    ("The city's first subway line opened in 1904", "most commuters kept riding streetcars for another twenty years", "contrast"),
    ("Octopuses have no bones", "they can crush the hard shells of crabs with their beaks", "contrast"),
    ("The desert receives less than five centimeters of rain in a typical year", "a single storm can turn its dry riverbeds into rushing streams within minutes", "contrast"),
    ("Early critics dismissed the novel as too long and too slow", "readers kept buying it, and it has never gone out of print", "contrast"),
    ("Most bats hunt insects at night", "the fruit bats of the region feed mainly on figs and mangoes", "contrast"),
    ("The bridge was designed to last fifty years", "engineers found serious cracks in its supports after only twelve", "contrast"),
    ("Glass looks perfectly smooth to the naked eye", "under a microscope its surface shows countless tiny ridges", "contrast"),
    ("The team's first prototype was fast and cheap to build", "it overheated after running for more than ten minutes", "contrast"),
    ("Honeybees are often assumed to be native to the Americas", "European settlers brought them across the Atlantic in the 1600s", "contrast"),
    ("The painter spent most of her career in a small coastal town", "her work was shown in galleries on three continents", "contrast"),
    ("Sound travels about 343 meters per second through air", "it moves more than four times faster through water", "contrast"),
    ("The school board expected the new schedule to reduce tardiness", "late arrivals rose slightly during the first semester", "contrast"),
    ("Mount Everest is the tallest mountain above sea level", "Mauna Kea is taller when measured from its base on the ocean floor", "contrast"),
    ("The recipe calls for fresh basil", "dried basil works nearly as well in the sauce", "contrast"),
    ("The composer wrote more than forty symphonies", "only three were performed during his lifetime", "contrast"),
    ("Most residents opposed the new highway at first", "many of them now use it every day to reach jobs in the city", "contrast"),
    ("Lightning usually strikes the tallest object in an area", "it sometimes hits open ground only a few meters from a tall tree", "contrast"),
    ("The museum's ancient coins are small and plain", "they draw larger crowds than any painting in the building", "contrast"),
    ("The first version of the app was downloaded millions of times", "few people kept using it after the first week", "contrast"),
    ("Penguins are birds", "none of the living species can fly", "contrast"),
    ("The captain had sailed the route dozens of times", "the thick fog that night left him unsure of the ship's position", "contrast"),
    ("Tomatoes are usually served as vegetables", "botanists classify them as fruits because they develop from flowers and contain seeds", "contrast"),
    ("The novelist rarely gave interviews", "she answered nearly every letter that readers sent her", "contrast"),
    ("The old factory closed in 1987", "its brick smokestack still towers over the neighborhood", "contrast"),
    ("Cheetahs can sprint at more than 100 kilometers per hour", "they can hold that speed for only about thirty seconds", "contrast"),
    ("The first trial of the experiment produced promising results", "the researchers could not reproduce them in the second trial", "contrast"),
    ("The island has no permanent residents", "scientists visit it every summer to count its nesting seabirds", "contrast"),
    ("The violin looked almost new", "records showed that it had been built more than two centuries earlier", "contrast"),
    ("Most deserts are hot", "the largest desert on Earth is the frozen continent of Antarctica", "contrast"),
    ("The mayor promised to finish the park by spring", "construction delays pushed its opening to late August", "contrast"),

    # ---- result ----
    ("Heavy rain fell on the valley for six straight days", "the river rose over its banks and flooded several farms", "result"),
    ("The bakery's ovens broke down early Saturday morning", "the shop sold only cold sandwiches that weekend", "result"),
    ("Sharp rocks damaged the rover's front wheels", "engineers planned a new route that avoided rough terrain", "result"),
    ("The concert sold out within minutes", "the band added a second show for the following night", "result"),
    ("Snow blocked the only road into the village", "supplies had to be delivered by helicopter for a week", "result"),
    ("The library received a large grant from a local foundation", "it was able to double its collection of audiobooks", "result"),
    ("Copper conducts electricity very efficiently", "it is widely used in household wiring", "result"),
    ("The inspection revealed rusted cables on the bridge", "the city closed it to heavy trucks until repairs were finished", "result"),
    ("The drought lasted three summers", "many farmers switched to crops that need less water", "result"),
    ("The team's best pitcher injured his shoulder in May", "he missed the rest of the season", "result"),
    ("The museum's roof began to leak during the storm", "staff moved dozens of paintings to a dry storage room", "result"),
    ("Ice is less dense than liquid water", "it floats on the surface of lakes and ponds", "result"),
    ("The company's new phone cost less than its rivals", "it quickly became the best-selling model in the country", "result"),
    ("The trail crosses a fragile wetland", "hikers must stay on the wooden boardwalk", "result"),
    ("The factory switched from coal to natural gas", "its carbon emissions fell by nearly half", "result"),
    ("The town's population doubled in ten years", "officials built two new elementary schools", "result"),
    ("The printer ran out of ink in the middle of the report", "the final pages came out almost blank", "result"),
    ("The glacier has been melting rapidly", "the lake below it has grown larger every year", "result"),
    ("The play received glowing reviews", "its run was extended by three months", "result"),
    ("The seeds were stored in a cold, dry vault", "most of them could still sprout decades later", "result"),
    ("The road across town was repaved last summer", "the drive now takes ten fewer minutes", "result"),
    ("The volcano had been rumbling for weeks", "authorities evacuated the nearby villages", "result"),
    ("The school's heating system failed in January", "classes were held online for three days", "result"),
    ("Aluminum is light and resists rust", "engineers often choose it for aircraft parts", "result"),
    ("The author's first draft was nearly 900 pages long", "her editor asked her to cut it by a third", "result"),
    ("The farm installed drip irrigation", "it now uses about 40 percent less water", "result"),
    ("The stadium lights were broken", "the evening game was moved to the afternoon", "result"),
    ("The clay in the region is rich in iron", "pottery made there has a deep red color", "result"),
    ("The ferry's engine failed halfway across the bay", "passengers waited two hours for a tugboat", "result"),
    ("The researchers' microphones kept picking up traffic noise", "they moved their recording station deeper into the forest", "result"),

    # ---- addition ----
    ("The library extended its weekend hours", "it added a homework help desk staffed by volunteers", "addition"),
    ("The new park includes a skate area", "it has a garden where residents can grow vegetables", "addition"),
    ("The scientist published three papers on coral reefs that year", "she testified before a state committee on ocean policy", "addition"),
    ("The museum's renovation added a rooftop terrace", "it created a gallery for rotating exhibits by local artists", "addition"),
    ("The bus line will run every ten minutes during rush hour", "it will extend its route to the airport", "addition"),
    ("The festival features live music on three stages", "it offers cooking classes taught by chefs from the region", "addition"),
    ("The phone's battery lasts two full days", "it charges to 80 percent in about half an hour", "addition"),
    ("The volunteers planted two hundred trees along the river", "they removed several tons of trash from its banks", "addition"),
    ("The coach added an extra practice on Saturdays", "she brought in a trainer to work on the players' endurance", "addition"),
    ("The composer wrote the film's entire score", "he conducted the orchestra that recorded it", "addition"),
    ("The town repaired the sidewalks on Main Street", "it installed new benches near the bus stops", "addition"),
    ("The new textbook includes practice problems after every lesson", "it provides worked solutions for half of them", "addition"),
    ("The hotel offers free breakfast", "guests can borrow bicycles at no charge", "addition"),
    ("The biologist tagged forty sea turtles during the study", "she collected blood samples from each one", "addition"),
    ("The recipe cuts the amount of sugar in half", "it replaces the butter with olive oil", "addition"),
    ("The architect designed the building's solar roof", "she planned a system that collects rainwater for its gardens", "addition"),
    ("The club hosts a chess tournament every spring", "it runs free lessons for beginners on Tuesday evenings", "addition"),
    ("The documentary won an award at a festival in Toronto", "it was nominated for two national prizes", "addition"),
    ("The rover measured the temperature of the soil", "it photographed layers of rock inside the crater", "addition"),
    ("The mayor lowered the fee for summer camps", "she expanded the number of spots available for teenagers", "addition"),
    ("The app lets users track how much water they drink", "it reminds them to take short walks during long workdays", "addition"),
    ("The new stadium seats forty thousand fans", "it includes a museum devoted to the team's history", "addition"),
    ("The students built a weather station on the school's roof", "they posted its readings online every hour", "addition"),
    ("The farm grows strawberries in the spring", "it sells pumpkins and apples in the fall", "addition"),
    ("The author visited ten schools on her tour", "she led writing workshops at three public libraries", "addition"),
    ("The telescope can detect infrared light", "it can measure the chemical makeup of distant atmospheres", "addition"),
    ("The company doubled its paid family leave", "it began offering free child care at its headquarters", "addition"),
    ("The orchestra performed two new works by local composers", "it invited high school musicians to join it for the final piece", "addition"),
    ("The trail was widened to allow wheelchairs", "shaded rest areas were added every kilometer", "addition"),
    ("The newspaper launched a weekly science section", "it hired two reporters to cover climate and health", "addition"),

    # ---- example ----
    ("Many animals change color with the seasons", "the arctic fox's brown summer coat turns white in winter", "example"),
    ("Some plants trap and digest insects", "the Venus flytrap snaps shut when an insect brushes the tiny hairs on its leaves", "example"),
    ("Several of the city's oldest buildings have been given new uses", "a former train station now houses a public market", "example"),
    ("Many common English words were borrowed from other languages", "the word \"kindergarten\" came directly from German", "example"),
    ("Some metals react strongly with water", "sodium can burst into flame when it touches water", "example"),
    ("Many professional musicians began performing as children", "the pianist who opened this year's festival gave her first concert at age seven", "example"),
    ("Small changes in design can make tools easier to use", "a slightly curved handle reduces strain on the wrist", "example"),
    ("Some birds migrate remarkable distances", "the arctic tern flies from the Arctic to the Antarctic and back every year", "example"),
    ("Several planets in the solar system have rings", "Saturn's rings are made mostly of chunks of ice", "example"),
    ("Many cities are reducing car traffic downtown", "several have closed central streets to cars on weekends", "example"),
    ("Some foods last a very long time without spoiling", "honey sealed in a jar can stay edible for decades", "example"),
    ("Many inventions came about by accident", "the microwave oven was developed after an engineer noticed that radar equipment had melted a candy bar in his pocket", "example"),
    ("Some trees live for thousands of years", "certain bristlecone pines in California are more than 4,000 years old", "example"),
    ("Many sports have changed their rules to improve safety", "some youth soccer leagues now limit heading the ball", "example"),
    ("Some animals use tools", "sea otters crack open shellfish by striking them against rocks balanced on their chests", "example"),
    ("Many towns celebrate their local crops", "one town in the valley holds a garlic festival every July", "example"),
    ("Some languages are written from right to left", "Arabic and Hebrew are both read in that direction", "example"),
    ("Many materials can be recycled more than once", "aluminum cans can be melted down and remade again and again", "example"),
    ("Some deserts bloom after rare rains", "parts of Chile's Atacama Desert fill with pink and purple flowers after an unusually wet winter", "example"),
    ("Several of the novelist's books were inspired by her travels", "her second novel is set in a fishing village she visited in Portugal", "example"),
    ("Many deep-sea creatures produce their own light", "the anglerfish uses a glowing lure to attract prey", "example"),
    ("Some buildings are designed to survive strong earthquakes", "certain towers rest on rubber bearings that absorb the ground's shaking", "example"),
    ("Many household products were first developed for other purposes", "bubble wrap was originally marketed as a textured wallpaper", "example"),
    ("Some reptiles can regrow lost body parts", "many lizards can grow a new tail after losing one to a predator", "example"),
    ("Many board games are centuries old", "an early version of chess was being played in India more than 1,400 years ago", "example"),
    ("Some mammals spend their entire lives in water", "manatees eat, sleep, and give birth without ever leaving rivers and coastal waters", "example"),
    ("Some cities have built parks on unusual sites", "one park in New York City runs along an old elevated railway", "example"),
    ("Many schools now teach students to write computer code", "some elementary schools introduce simple programming games in first grade", "example"),
    ("Some fruits keep ripening after they are picked", "bananas picked green will turn yellow on a kitchen counter", "example"),
    ("Many scientists now share their data openly", "the team that mapped the reef posted every one of its measurements online", "example"),
]

# (subject, appositive noun phrase that renames it, predicate starting with a verb)
APPOSITIVES = [
    ("The town's oldest bakery", "a narrow brick building on Elm Street", "has sold the same rye bread since 1952"),
    ("Dr. Lena Ortiz", "the lead engineer on the bridge project", "presented the final design to the city council"),
    ("The expedition's ship", "a converted fishing trawler", "carried twelve scientists and their equipment"),
    ("Jupiter", "the largest planet in the solar system", "has dozens of known moons"),
    ("The school's robotics team", "a group of eleven students", "won the regional competition in March"),
    ("Quinoa", "a seed that is cooked and eaten like a grain", "was first grown in the Andes thousands of years ago"),
    ("The festival's headliner", "a jazz trio from New Orleans", "played for nearly three hours"),
    ("Marcus Hale", "the author of four mystery novels", "grew up in a lighthouse on the Maine coast"),
    ("The city's newest museum", "a glass building shaped like a wave", "opened to the public last spring"),
    ("Basalt", "a dark volcanic rock", "forms when lava cools quickly near the surface"),
    ("The committee's report", "a forty-page document", "recommended building two new fire stations"),
    ("Amara Singh", "a marine biologist at the coastal research center", "studies how sea stars recover from disease"),
    ("The river's main channel", "a stretch of water more than a kilometer wide", "is dredged every year to keep ships moving"),
    ("The violinist's instrument", "a gift from her grandfather", "was built in Italy in the 1700s"),
    ("Mercury", "the planet closest to the Sun", "completes an orbit in just 88 Earth days"),
    ("The library's rarest book", "a hand-copied atlas", "is displayed under glass near the entrance"),
    ("Coach Rivera", "a former professional sprinter", "trains the team six days a week"),
    ("The new vaccine", "a single-dose shot", "can be stored in an ordinary refrigerator"),
    ("The garden's centerpiece", "a fountain carved from white stone", "was restored by volunteers last summer"),
    ("Tomás Ferreira", "the youngest member of the orchestra", "played a solo at the season's opening concert"),
    ("The company's first product", "a folding bicycle", "sold out within a month"),
    ("Graphite", "the soft gray material in pencils", "is made of carbon atoms arranged in flat sheets"),
    ("The old mill", "a three-story wooden building beside the creek", "now houses a pottery studio"),
    ("The team's captain", "a senior who has played since seventh grade", "scored the winning goal"),
    ("The town's only theater", "a small stage above the hardware store", "hosts a new play every month"),
    ("Photosynthesis", "the process plants use to make sugar from sunlight", "also releases oxygen into the air"),
    ("The bridge's designer", "an engineer named Ruth Adeyemi", "insisted on using local stone"),
    ("The expedition's leader", "a geologist with thirty years of experience", "chose the route across the glacier"),
    ("Our science teacher", "a former NASA intern", "brought a real meteorite to class"),
    ("The rainforest's tallest tree", "a kapok more than sixty meters high", "shelters dozens of bird species in its branches"),
    ("The novel's narrator", "a retired sea captain", "tells the story through letters to his daughter"),
    ("The school's new principal", "a former math teacher", "visited every classroom during her first week"),
    ("The museum's newest exhibit", "a collection of handmade kites from twelve countries", "fills the entire second floor"),
    ("Kelp", "a type of large brown seaweed", "can grow more than half a meter in a single day"),
    ("The farm's oldest tractor", "a red machine built in 1949", "still runs every harvest season"),
    ("The mayor's plan", "a proposal to add bike lanes to every major street", "passed by a single vote"),
    ("The band's drummer", "a self-taught musician from Detroit", "wrote most of the album's songs"),
    ("The study's main finding", "a link between sleep and memory", "surprised few of the researchers"),
    ("The village's well", "a stone shaft more than forty meters deep", "has never run dry"),
    ("The chef's signature dish", "a soup made with roasted corn and peppers", "appears on the menu every day"),
    ("The lighthouse keeper", "a woman named Ida Lewis", "rescued more than a dozen people from the water"),
    ("The project's budget", "about two million dollars", "covered the cost of new equipment"),
    ("Our town's newspaper", "a weekly paper founded in 1880", "is still printed on a press in the basement"),
    ("The comet", "a ball of ice and dust several kilometers wide", "will pass closest to the Sun next spring"),
    ("The documentary's director", "a former wildlife photographer", "spent two years filming in the Arctic"),
    ("The hospital's newest wing", "a five-story building for children", "opened in January"),
    ("The park's oldest oak", "a tree more than three hundred years old", "was struck by lightning last summer"),
    ("The team's new stadium", "a domed arena near the waterfront", "will hold forty thousand fans"),
    ("The poet's first book", "a slim collection of sonnets", "sold only two hundred copies"),
    ("The research station", "a cluster of small buildings on the ice", "houses about thirty scientists in the winter"),
    ("Obsidian", "a glassy black rock", "forms when lava cools too quickly for crystals to grow"),
    ("The bakery's owner", "a former chemistry teacher", "measures every ingredient to the gram"),
    ("The city's first mayor", "a merchant named Elias Brandt", "served for only eleven months"),
    ("The festival's mascot", "a giant papier-mâché fish", "leads the parade each year"),
    ("The ship's cargo", "several hundred crates of tea", "was worth a fortune at the time"),
    ("The game's final level", "a maze of moving platforms", "takes most players hours to finish"),
    ("The class's field trip", "a visit to the state capitol", "was postponed because of snow"),
    ("The orchestra's conductor", "a composer in her own right", "added one of her own pieces to the program"),
    ("The recipe's secret ingredient", "a pinch of smoked salt", "gives the stew its rich flavor"),
    ("The island's only road", "a narrow gravel track", "circles the coast in about twenty kilometers"),
    ("The telescope's main mirror", "a disk more than eight meters across", "was polished for nearly two years"),
    ("The mural's artist", "a painter who grew up in the neighborhood", "included portraits of local shop owners"),
    ("The town's annual race", "a ten-kilometer run through the hills", "draws runners from across the state"),
    ("The seed vault", "a storage facility dug into a frozen mountain", "protects copies of crops from around the world"),
    ("The team's mascot", "a golden retriever named Biscuit", "attends every home game"),
    ("The inventor's notebook", "a leather journal filled with sketches", "sold at auction for a record price"),
    ("The debate's final speaker", "a sophomore from the visiting school", "earned the highest score of the day"),
    ("The canal", "a waterway dug by hand in the 1820s", "once carried grain from the farms to the city"),
    ("The museum's guide", "a retired history professor", "knows the story behind every object in the collection"),
    ("The forest's largest predator", "a lynx that visitors rarely see", "hunts mainly snowshoe hares"),
    ("The app's latest update", "a version with a simpler menu", "fixed most of the problems users had reported"),
    ("The school's garden", "a plot behind the gym", "supplies vegetables to the cafeteria each fall"),
    ("The lecture's speaker", "an astronomer who studies distant galaxies", "answered questions for an hour afterward"),
    ("The first bicycle", "a wooden machine with no pedals", "was pushed along by the rider's feet"),
    ("The novel's villain", "a charming but dishonest banker", "fools nearly every other character"),
    ("The play's set", "a single room with a tilted floor", "made the audience feel slightly off balance"),
    ("The storm", "the strongest to hit the coast in fifty years", "knocked out power to thousands of homes"),
    ("The city's water tower", "a steel tank painted to look like a hot-air balloon", "has become a local landmark"),
    ("The runner's coach", "her older brother", "timed every lap from the bleachers"),
    ("The company's founder", "a former mail carrier", "started the business in her garage"),
    ("The survey's results", "responses from more than two thousand students", "will be published next month"),
    ("The river's source", "a spring high in the mountains", "is only a few meters wide"),
    ("The quilt", "a patchwork of fabric from three generations of the family", "hangs in the museum's entrance hall"),
    ("The robot's arm", "a jointed metal limb with a gripper at the end", "can lift objects as heavy as twenty kilograms"),
    ("The city's oldest bridge", "a stone arch built by Roman engineers", "still carries foot traffic today"),
    ("The cafe's owner", "a woman who once worked as a ship's cook", "bakes all the bread herself"),
    ("The fossil", "a nearly complete skeleton of an early whale", "was found in a desert far from any ocean"),
    ("The pianist's encore", "a short piece by a little-known composer", "brought the audience to its feet"),
    ("The trail's final section", "a steep climb over loose rock", "takes most hikers about an hour"),
    ("The school's oldest trophy", "a silver cup from 1921", "sits in a case outside the principal's office"),
    ("The satellite", "a spacecraft about the size of a school bus", "will map the ocean floor"),
    ("The garden's rarest plant", "an orchid that blooms only once every few years", "attracted hundreds of visitors this week"),
    ("The city's new library", "a building made mostly of wood", "was finished in just fourteen months"),
    ("The festival's founder", "a retired music teacher", "still introduces every performer"),
    ("The museum's oldest map", "a chart drawn on sheepskin", "shows coastlines that no longer exist"),
    ("The warehouse's new robot", "a machine that can sort a thousand parcels an hour", "works alongside twelve human employees"),
    ("The cave's largest chamber", "a space big enough to hold a cathedral", "was discovered only recently"),
    ("The coach's strategy", "a defense that pressures the ball all game", "wore out the other team by halftime"),
    ("The volcano's crater", "a bowl nearly two kilometers wide", "holds a bright green lake"),
    ("The contest's winner", "a ninth grader from a rural school", "designed a water filter made from sand and charcoal"),
]
