"""Sentence bank for the grammar generator, part B: agreement, form, and structure.

All sentences are original. See gen_grammar.py for how each entry becomes a question.
"""

S, P = "singular", "plural"

# Verb forms: base -> (third-person singular, -ing form, past participle)
VERBS = {
    "offer": ("offers", "offering", "offered"), "include": ("includes", "including", "included"),
    "suggest": ("suggests", "suggesting", "suggested"), "depend": ("depends", "depending", "depended"),
    "feature": ("features", "featuring", "featured"), "contain": ("contains", "containing", "contained"),
    "leave": ("leaves", "leaving", "left"), "show": ("shows", "showing", "shown"),
    "remain": ("remains", "remaining", "remained"), "rise": ("rises", "rising", "risen"),
    "sit": ("sits", "sitting", "sat"), "carry": ("carries", "carrying", "carried"),
    "read": ("reads", "reading", "read"), "make": ("makes", "making", "made"),
    "meet": ("meets", "meeting", "met"), "rely": ("relies", "relying", "relied"),
    "avoid": ("avoids", "avoiding", "avoided"), "hang": ("hangs", "hanging", "hung"),
    "nest": ("nests", "nesting", "nested"), "exceed": ("exceeds", "exceeding", "exceeded"),
    "attract": ("attracts", "attracting", "attracted"), "move": ("moves", "moving", "moved"),
    "practice": ("practices", "practicing", "practiced"), "explain": ("explains", "explaining", "explained"),
    "cover": ("covers", "covering", "covered"), "help": ("helps", "helping", "helped"),
    "belong": ("belongs", "belonging", "belonged"), "guide": ("guides", "guiding", "guided"),
    "brighten": ("brightens", "brightening", "brightened"), "review": ("reviews", "reviewing", "reviewed"),
    "threaten": ("threatens", "threatening", "threatened"), "continue": ("continues", "continuing", "continued"),
    "allow": ("allows", "allowing", "allowed"), "record": ("records", "recording", "recorded"),
    "provide": ("provides", "providing", "provided"), "date": ("dates", "dating", "dated"),
    "stand": ("stands", "standing", "stood"), "rehearse": ("rehearses", "rehearsing", "rehearsed"),
    "block": ("blocks", "blocking", "blocked"), "wear": ("wears", "wearing", "worn"),
    "spin": ("spins", "spinning", "spun"), "face": ("faces", "facing", "faced"),
    "extend": ("extends", "extending", "extended"), "spread": ("spreads", "spreading", "spread"),
    "reveal": ("reveals", "revealing", "revealed"), "change": ("changes", "changing", "changed"),
    "require": ("requires", "requiring", "required"), "fall": ("falls", "falling", "fallen"),
    "arrive": ("arrives", "arriving", "arrived"), "walk": ("walks", "walking", "walked"),
    "wind": ("winds", "winding", "wound"), "come": ("comes", "coming", "come"),
    "lead": ("leads", "leading", "led"), "focus": ("focuses", "focusing", "focused"),
    "lie": ("lies", "lying", "lain"), "hold": ("holds", "holding", "held"),
    "reach": ("reaches", "reaching", "reached"), "celebrate": ("celebrates", "celebrating", "celebrated"),
    "ring": ("rings", "ringing", "rung"), "hatch": ("hatches", "hatching", "hatched"),
    "need": ("needs", "needing", "needed"), "tell": ("tells", "telling", "told"),
    "plan": ("plans", "planning", "planned"), "share": ("shares", "sharing", "shared"),
    "erode": ("erodes", "eroding", "eroded"), "agree": ("agrees", "agreeing", "agreed"),
    "slow": ("slows", "slowing", "slowed"), "keep": ("keeps", "keeping", "kept"),
    "fill": ("fills", "filling", "filled"), "warn": ("warns", "warning", "warned"),
    "draw": ("draws", "drawing", "drawn"), "end": ("ends", "ending", "ended"),
    "grow": ("grows", "growing", "grown"), "capture": ("captures", "capturing", "captured"),
}

# (full subject, head word the verb agrees with, number, verb base, rest of sentence)
# "be" is handled separately: is/are.
AGREEMENT = [
    ("The collection of letters, photographs, and diaries", "collection", S, "offer", "a rare view of daily life during the war"),
    ("The list of approved field trips for the spring semester", "list", S, "include", "a visit to the aquarium"),
    ("A series of small earthquakes along the coast", "series", S, "suggest", "that pressure is building beneath the seafloor"),
    ("The quality of the city's parks", "quality", S, "depend", "largely on volunteer work"),
    ("Each of the museum's galleries", "Each", S, "feature", "work from a different century"),
    ("The number of students who ride the bus to school", "number", S, "be", "higher this year than ever before"),
    ("The stack of old newspapers in the basement", "stack", S, "contain", "headlines from nearly a century of local history"),
    ("The flock of geese on the pond", "flock", S, "leave", "every October for warmer wetlands to the south"),
    ("The team's analysis of forty rivers", "analysis", S, "show", "that pollution levels have fallen since 2010"),
    ("One of the city's oldest bridges", "One", S, "remain", "closed to traffic"),
    ("The price of concert tickets", "price", S, "rise", "sharply whenever a tour is announced"),
    ("A bowl of ripe peaches", "bowl", S, "sit", "on the kitchen table"),
    ("The sound of the waves against the rocks", "sound", S, "carry", "all the way to the village"),
    ("The author's account of her travels through the mountains", "account", S, "read", "like an adventure novel"),
    ("The combination of heat and humidity", "combination", S, "make", "the summer months hard on outdoor workers"),
    ("The team of engineers and designers", "team", S, "meet", "every Monday to review its progress"),
    ("The success of the city's recycling programs", "success", S, "rely", "on residents sorting their trash correctly"),
    ("Neither of the proposed routes", "Neither", S, "avoid", "the busy downtown streets"),
    ("The main source of the region's rivers", "source", S, "be", "snowmelt from the surrounding peaks"),
    ("The painting of the two sisters", "painting", S, "hang", "in the museum's main hall"),
    ("The cost of the new laboratories", "cost", S, "exceed", "the school's original budget"),
    ("The library's collection of rare maps", "collection", S, "attract", "researchers from around the world"),
    ("The swarm of bees near the orchard", "swarm", S, "move", "to a new hive each spring"),
    ("Every one of the players on the roster", "one", S, "practice", "at least four days a week"),
    ("The history of the region's railroads", "history", S, "explain", "why the towns are spaced so evenly"),
    ("The migration of monarch butterflies", "migration", S, "cover", "thousands of kilometers each year"),
    ("The use of drones by farmers", "use", S, "help", "them spot crop disease early"),
    ("The box of old tools in the garage", "box", S, "belong", "to my grandfather"),
    ("The steady rhythm of the drums", "rhythm", S, "guide", "the dancers through each step"),
    ("A study of sleep habits among teenagers", "study", S, "suggest", "that later school start times improve attendance"),
    ("The bouquet of wildflowers", "bouquet", S, "brighten", "the otherwise plain room"),
    ("The committee of teachers and parents", "committee", S, "review", "every proposal before the board votes"),
    ("The arrival of new species in the lake", "arrival", S, "threaten", "the native fish"),
    ("The debate over the city's parking rules", "debate", S, "continue", "to divide local business owners"),
    ("The shape of the albatross's long wings", "shape", S, "allow", "it to glide for hours without flapping"),
    ("The flow of traffic through the tunnels", "flow", S, "slow", "during rush hour"),
    ("The noise from the construction sites", "noise", S, "keep", "residents awake at night"),
    ("The group of hikers", "group", S, "reach", "the summit before noon on most days"),
    ("The smell of fresh bread and coffee", "smell", S, "fill", "the street outside the bakery each morning"),
    ("The report on the region's forests", "report", S, "warn", "that wildfires are becoming more frequent"),
    ("The design of the new bridges", "design", S, "draw", "on ideas from ancient Roman arches"),
    ("The river's journey through three countries", "journey", S, "end", "at a wide, marshy delta"),
    ("The value of the old coins", "value", S, "grow", "a little each year"),
    ("The recording of the two concerts", "recording", S, "capture", "the energy of the live performances"),
    ("The layers of rock in the canyon", "layers", P, "record", "millions of years of the region's history"),
    ("The trees along the edge of the old farm", "trees", P, "provide", "shade for the grazing cattle"),
    ("The paintings in the museum's east wing", "paintings", P, "date", "from the early 1800s"),
    ("The results of the survey", "results", P, "suggest", "that most students want a longer lunch period"),
    ("The walls of the ancient city", "walls", P, "stand", "more than ten meters high"),
    ("The members of the jazz band", "members", P, "rehearse", "in the school's music room"),
    ("The instructions on the back of the box", "instructions", P, "be", "difficult to follow"),
    ("The effects of the new policy", "effects", P, "be", "already visible in the city's budget"),
    ("The fossils found near the base of the cliff", "fossils", P, "belong", "to an early species of horse"),
    ("The cars parked along the narrow street", "cars", P, "block", "the delivery trucks"),
    ("The students in the chemistry class", "students", P, "wear", "safety goggles during every experiment"),
    ("The plans for the new stadium", "plans", P, "include", "a retractable roof"),
    ("The seeds of the maple tree", "seeds", P, "spin", "like tiny helicopters as they fall"),
    ("The windows of the old library", "windows", P, "face", "the river"),
    ("The questions on the final exam", "questions", P, "cover", "every unit of the course"),
    ("The benefits of regular exercise", "benefits", P, "extend", "well beyond physical health"),
    ("The roots of the giant oak", "roots", P, "spread", "under the entire lawn"),
    ("The artifacts discovered at the site", "artifacts", P, "reveal", "details about ancient trade routes"),
    ("The lights on the bridge", "lights", P, "change", "color every evening"),
    ("The rules of the tournament", "rules", P, "require", "each player to keep score"),
    ("The costs of repairing the road", "costs", P, "fall", "on the county"),
    ("The birds that visit the feeder", "birds", P, "arrive", "just after sunrise"),
    ("The photographs in the album", "photographs", P, "show", "the town before the flood"),
    ("The volunteers at the animal shelter", "volunteers", P, "walk", "the dogs twice a day"),
    ("The streets of the old town", "streets", P, "wind", "up the hillside in tight curves"),
    ("The reasons for the delay", "reasons", P, "remain", "unclear"),
    ("The ingredients in the sauce", "ingredients", P, "come", "from farms within fifty kilometers"),
    ("The guides at the national park", "guides", P, "lead", "hikes to the waterfall every morning"),
    ("The chapters in the second half of the book", "chapters", P, "focus", "on the author's childhood"),
    ("The players on the visiting team", "players", P, "be", "taller than ours"),
    ("The stars in the constellation", "stars", P, "lie", "at very different distances from Earth"),
    ("The fees for the summer program", "fees", P, "cover", "meals and transportation"),
    ("The shelves in the back of the store", "shelves", P, "hold", "the discounted books"),
    ("The waves during the storm", "waves", P, "reach", "heights of six meters"),
    ("The murals on the side of the building", "murals", P, "celebrate", "the neighborhood's history"),
    ("The bells in the tower", "bells", P, "ring", "every hour"),
    ("The eggs of the sea turtle", "eggs", P, "hatch", "after about two months"),
    ("The engines of the old ship", "engines", P, "need", "constant repair"),
    ("The songs on the band's first album", "songs", P, "tell", "the story of a single summer"),
    ("The teachers at the school", "teachers", P, "hold", "office hours on Thursdays"),
    ("The coach and her assistant", "coach and her assistant", P, "plan", "every practice together"),
    ("The museum and the library", "museum and the library", P, "share", "a parking lot"),
    ("Rain and wind", "Rain and wind", P, "erode", "the cliffs a little more each year"),
    ("The mayor and the city council", "mayor and the city council", P, "agree", "on the need for more housing"),
]

# (sentence with ___ for the possessive pronoun, antecedent, number, difficulty)
PRONOUNS = [
    ("The committee announced ___ decision after a two-hour meeting.", "committee", S, "medium"),
    ("Each of the valleys in the region has ___ own dialect.", "Each", S, "hard"),
    ("The company moved ___ headquarters to a converted warehouse.", "company", S, "easy"),
    ("The school celebrated ___ hundredth anniversary with a parade.", "school", S, "easy"),
    ("After the storm, the town spent months repairing ___ harbor.", "town", S, "easy"),
    ("The jury reached ___ verdict late on Friday afternoon.", "jury", S, "medium"),
    ("The river changes ___ course slightly after every major flood.", "river", S, "easy"),
    ("The museum lends several of ___ paintings to smaller galleries each year.", "museum", S, "medium"),
    ("The band released ___ third album in the fall.", "band", S, "medium"),
    ("A hummingbird can beat ___ wings more than fifty times per second.", "hummingbird", S, "easy"),
    ("The team lost ___ first game but won the next six.", "team", S, "medium"),
    ("The city updated ___ recycling rules to include plastic bags.", "city", S, "easy"),
    ("The orchestra ended ___ season with a free outdoor concert.", "orchestra", S, "medium"),
    ("The tree drops ___ leaves earlier than the other maples on the street.", "tree", S, "medium"),
    ("The newspaper corrected ___ error in the next day's edition.", "newspaper", S, "easy"),
    ("The university named ___ new library after a former student.", "university", S, "easy"),
    ("The spider rebuilds ___ web every evening.", "spider", S, "easy"),
    ("The government raised ___ estimate of the harvest after the rains.", "government", S, "medium"),
    ("Neither of the bridges has reached the end of ___ expected lifespan.", "Neither", S, "hard"),
    ("The class donated ___ bake-sale earnings to the animal shelter.", "class", S, "medium"),
    ("The volcano last erupted in 1956, and ___ crater has been quiet ever since.", "volcano", S, "medium"),
    ("The factory cut ___ water use by recycling cooling water.", "factory", S, "easy"),
    ("The robot uses ___ camera to avoid obstacles.", "robot", S, "easy"),
    ("The planet takes 165 years to complete ___ orbit around the Sun.", "planet", S, "easy"),
    ("Every one of the new buses has a ramp at ___ rear door.", "one", S, "hard"),
    ("The farm sells most of ___ eggs at the Saturday market.", "farm", S, "easy"),
    ("The website redesigned ___ home page so that it loads faster.", "website", S, "easy"),
    ("The state protects ___ remaining wetlands under a 1990 law.", "state", S, "easy"),
    ("The ship lowered ___ lifeboats during the drill.", "ship", S, "easy"),
    ("The novel takes ___ title from a line in an old folk song.", "novel", S, "medium"),
    ("The critics praised the film for ___ bold use of color.", "film", S, "hard"),
    ("The researchers published ___ findings in a medical journal.", "researchers", P, "easy"),
    ("The students presented ___ projects at the science fair.", "students", P, "easy"),
    ("Both of the candidates explained ___ plans for the city's budget.", "Both", P, "medium"),
    ("Many birds line ___ nests with soft feathers.", "birds", P, "easy"),
    ("The twins celebrated ___ birthday at the beach.", "twins", P, "easy"),
    ("Several of the actors forgot ___ lines during the first rehearsal.", "Several", P, "medium"),
    ("The museum's visitors can leave ___ coats at the front desk.", "visitors", P, "medium"),
    ("The engineers tested ___ design in a wind tunnel.", "engineers", P, "easy"),
    ("The whales return to ___ breeding grounds every winter.", "whales", P, "easy"),
    ("The scientists and their assistants recorded ___ observations in a shared notebook.", "scientists and their assistants", P, "medium"),
    ("The authors signed copies of ___ books after the talk.", "authors", P, "easy"),
    ("The two companies merged ___ research divisions last year.", "companies", P, "easy"),
    ("Honeybees tell ___ hivemates where to find flowers by performing a dance.", "Honeybees", P, "easy"),
    ("The countries in the treaty agreed to reduce ___ fishing fleets.", "countries", P, "medium"),
    ("The volunteers brought ___ own tools to the cleanup.", "volunteers", P, "easy"),
    ("The pilots checked ___ instruments before takeoff.", "pilots", P, "easy"),
    ("Wolves mark the edges of ___ territory with scent.", "Wolves", P, "easy"),
    ("The astronauts spent ___ first night in orbit testing equipment.", "astronauts", P, "easy"),
    ("The sisters opened ___ first restaurant in 2015.", "sisters", P, "easy"),
]

# (sentence with ___ before the thing owned, singular owner, plural owner, number)
POSSESSIVES = [
    ("Our town has only one library, and the ___ reading room stays open until midnight.", "library", "libraries", S),
    ("The old ___ captain ordered the crew to lower its sails.", "ship", "ships", S),
    ("The ___ tail twitched as it watched the birds outside the window.", "cat", "cats", S),
    ("The ___ final report, which it released on Monday, recommends a new bridge.", "committee", "committees", S),
    ("The ___ new uniforms arrived just before its first game.", "team", "teams", S),
    ("Every ___ owner must register it with the county.", "boat", "boats", S),
    ("My ___ engine sputtered as I drove it up the steep hill.", "truck", "trucks", S),
    ("The ___ only entrance is a narrow door on its north side.", "fort", "forts", S),
    ("A ___ wings can beat more than fifty times per second.", "hummingbird", "hummingbirds", S),
    ("The ___ lead actor forgot a line on its opening night.", "play", "plays", S),
    ("Each ___ cover was designed by a different artist.", "book", "books", S),
    ("The ___ smell drifted down the street as it baked its first loaves of the day.", "bakery", "bakeries", S),
    ("Our ___ surface is covered with craters that formed billions of years ago.", "moon", "moons", S),
    ("The ___ founder started it in a small garage.", "company", "companies", S),
    ("A single ___ roots can spread wider than its branches.", "tree", "trees", S),
    ("The ___ mayor lives in a house near its central square.", "city", "cities", S),
    ("Her only ___ strings snapped just before the solo.", "violin", "violins", S),
    ("The ___ newest exhibit fills its entire second floor.", "museum", "museums", S),
    ("The ___ population has doubled since its new factory opened.", "town", "towns", S),
    ("The ___ leaves turn red in October, earlier than those of any other tree in the yard.", "maple", "maples", S),
    ("The ___ design won an award for its use of recycled steel.", "bridge", "bridges", S),
    ("This ___ price has dropped since its release last year.", "phone", "phones", S),
    ("The ___ headline, printed in huge letters across its front page, announced the election results.", "newspaper", "newspapers", S),
    ("The ___ nest sat on a ledge high above its hunting grounds.", "eagle", "eagles", S),
    ("That ___ last line is the most famous sentence its author ever wrote.", "novel", "novels", S),
    ("The ___ nests, which they build from mud, cling to the barn's rafters.", "swallow", "swallows", P),
    ("The two ___ captains, one from each side, shook hands before the match.", "team", "teams", P),
    ("Several ___ roofs were damaged by hail.", "house", "houses", P),
    ("The ___ lockers, which they share in pairs, line the hallway.", "student", "students", P),
    ("Many ___ populations have recovered since they were protected.", "whale", "whales", P),
    ("All twelve ___ covers, one for each book in the series, were designed by the same artist.", "book", "books", P),
    ("The ___ leaders, one from each of the five nations, met to sign the agreement.", "country", "countries", P),
    ("The ___ owners, one from each of the seven stores on the block, attended the meeting.", "store", "stores", P),
    ("Both ___ shells were cracked.", "egg", "eggs", P),
    ("The ___ nests, which the birds build in huge colonies, cover the cliff.", "gull", "gulls", P),
    ("Each of the three ___ homes was damaged in the flood.", "family", "families", P),
    ("The ___ migration routes, which the birds follow every year, cross three continents.", "stork", "storks", P),
    ("The ___ reports, one from each agency, reached opposite conclusions.", "agency", "agencies", P),
]

# Irregular plurals: (sentence, singular, plural)
IRREGULAR_POSSESSIVES = [
    ("The ___ section of the library is on the first floor.", "child", "children"),
    ("The ___ soccer team won the state title.", "woman", "women"),
    ("The ___ choice award went to a short film about bees.", "person", "people"),
    ("All ___ front teeth grow throughout their lives, so the animals must gnaw constantly.", "mouse", "mice"),
    ("The ___ locker room was repainted over the summer.", "man", "men"),
]

# (sentence with ___, correct verb, three wrong verbs, why)
TENSE = [
    ("Last summer, the city ___ new bike lanes on three downtown streets.", "painted", ["paints", "will paint", "has been painting"], "\"Last summer\" places the action in the finished past, so the simple past \"painted\" fits."),
    ("By the time the firefighters arrived, the flames ___ to the barn next door.", "had spread", ["spreads", "have spread", "will spread"], "The spreading happened before another past event (the firefighters' arrival), so the past perfect \"had spread\" is needed."),
    ("Every morning, the ferry ___ the island at exactly 6:15.", "leaves", ["left", "had left", "will have left"], "\"Every morning\" describes a habit, so the simple present \"leaves\" fits."),
    ("Next year, the museum ___ a new wing devoted to local artists.", "will open", ["opened", "has opened", "had opened"], "\"Next year\" points to the future, so \"will open\" is needed."),
    ("Since 2015, the town ___ its population double.", "has seen", ["saw", "sees", "had seen"], "\"Since 2015\" describes something that began in the past and continues now, which calls for the present perfect \"has seen.\""),
    ("In 1969, astronauts ___ on the Moon for the first time.", "landed", ["land", "have landed", "will land"], "\"In 1969\" is a specific past date, so the simple past \"landed\" fits."),
    ("The researchers ___ the data for three months before they noticed the pattern.", "had been analyzing", ["are analyzing", "will analyze", "analyze"], "The analysis went on before another past event (noticing the pattern), so the past perfect progressive \"had been analyzing\" fits."),
    ("As I write this letter, the rain ___ against the window.", "is tapping", ["tapped", "had tapped", "will tap"], "\"As I write\" shows the action is happening right now, so the present progressive \"is tapping\" fits."),
    ("When the bell rang, the students ___ their books and left.", "closed", ["close", "will close", "have closed"], "The sentence tells about finished past events (\"rang,\" \"left\"), so the simple past \"closed\" keeps the tenses consistent."),
    ("By next June, the crew ___ the new tunnel.", "will have finished", ["finished", "had finished", "has finished"], "\"By next June\" sets a future deadline, so the future perfect \"will have finished\" fits."),
    ("For the past decade, the orchestra ___ a free concert in the park every July.", "has performed", ["performed", "had performed", "will perform"], "\"For the past decade\" describes a repeated action that continues up to now, so the present perfect \"has performed\" fits."),
    ("Two centuries ago, most people in the region ___ their own food.", "grew", ["grow", "have grown", "will grow"], "\"Two centuries ago\" places the action in the past, so \"grew\" fits."),
    ("The comet ___ again in about seventy-six years.", "will appear", ["appeared", "has appeared", "had appeared"], "\"In about seventy-six years\" refers to the future, so \"will appear\" fits."),
    ("Before she became a novelist, Ana ___ as a nurse for ten years.", "had worked", ["works", "will work", "has worked"], "Her nursing came before another past event (becoming a novelist), so the past perfect \"had worked\" fits."),
    ("Right now, the team ___ for its final game of the season.", "is preparing", ["prepared", "had prepared", "will have prepared"], "\"Right now\" signals an action in progress, so the present progressive \"is preparing\" fits."),
    ("Yesterday, the wind ___ so hard that the ferry stayed in port.", "blew", ["blows", "has blown", "will blow"], "\"Yesterday\" and the past-tense \"stayed\" show a finished past event, so \"blew\" fits."),
    ("Scientists ___ the ocean floor for decades, yet much of it remains unmapped.", "have studied", ["study", "will study", "had studied"], "\"For decades\" together with \"remains\" describes study that began in the past and continues now, so the present perfect \"have studied\" fits."),
    ("Tomorrow, the students ___ their projects to a panel of engineers.", "will present", ["presented", "have presented", "had presented"], "\"Tomorrow\" points to the future, so \"will present\" fits."),
    ("The bridge ___ in 1932 and still carries traffic today.", "opened", ["opens", "has opened", "will open"], "\"In 1932\" is a specific past date, so the simple past \"opened\" fits. The present perfect can't be paired with a specific past date."),
    ("Whenever it snows, the school ___ an hour later than usual.", "opens", ["opened", "had opened", "will have opened"], "\"Whenever it snows\" describes a general pattern in the present, so \"opens\" fits."),
    ("After the team ___ the final match, the fans rushed onto the field.", "had won", ["wins", "will win", "has won"], "Winning happened before the fans rushed onto the field, and both are in the past, so \"had won\" fits."),
    ("By the end of next month's tour, the band ___ in forty cities.", "will have played", ["plays", "played", "has played"], "\"Next month's tour\" is in the future, and \"by the end of\" marks a deadline, so the future perfect \"will have played\" fits."),
    ("Ancient Egyptians ___ papyrus to make paper, rope, and boats.", "used", ["use", "will use", "have used"], "The sentence describes people of the distant past, so the simple past \"used\" fits."),
    ("At this moment, the rover ___ a crater on the planet's surface.", "is exploring", ["explored", "had explored", "will have explored"], "\"At this moment\" signals an action happening now, so \"is exploring\" fits."),
    ("Once the paint dries, the workers ___ the second coat.", "will apply", ["applied", "had applied", "have applied"], "\"Once the paint dries\" describes a future condition, so the result also belongs in the future: \"will apply.\""),
    ("While the audience ___ its seats, the orchestra tuned its instruments.", "was taking", ["takes", "will take", "has taken"], "The two actions happened at the same time in the past (\"tuned\"), so the past progressive \"was taking\" fits."),
    ("The museum ___ closed since the flood damaged its lower floor last spring.", "has been", ["was", "is", "will be"], "\"Since\" followed by a past event marks a state that continues now, so the present perfect \"has been\" fits."),
    ("Last night, the storm ___ power to thousands of homes.", "knocked out", ["knocks out", "will knock out", "has knocked out"], "\"Last night\" places the action in the finished past, so \"knocked out\" fits."),
    ("Each spring, the river ___ its banks and floods the low fields.", "overflows", ["overflowed", "had overflowed", "will have overflowed"], "\"Each spring\" and the present-tense \"floods\" describe a repeated pattern, so \"overflows\" fits."),
    ("Three years from now, the new library ___ its doors.", "will open", ["opened", "has opened", "had opened"], "\"Three years from now\" is in the future, so \"will open\" fits."),
    ("The author ___ four novels before her first one was published.", "had written", ["writes", "has written", "will write"], "The writing came before another past event (publication), so the past perfect \"had written\" fits."),
    ("During the 1800s, the town ___ a busy port for whaling ships.", "was", ["is", "has been", "will be"], "\"During the 1800s\" places the description in the past, so \"was\" fits."),
    ("The coach says that the team ___ harder than ever this season.", "is practicing", ["practiced", "had practiced", "was practicing"], "\"Says\" and \"this season\" place the action in the present, so the present progressive \"is practicing\" fits."),
    ("Before the telescope was invented, astronomers ___ only the stars visible to the naked eye.", "could study", ["can study", "will study", "have studied"], "The sentence describes a time in the past, so the past form \"could study\" fits."),
    ("When the power went out, we ___ dinner by candlelight.", "ate", ["eat", "will eat", "have eaten"], "The sentence tells about a finished past event (\"went out\"), so the simple past \"ate\" keeps the tenses consistent."),
    ("Since the new schedule began, attendance ___ steadily.", "has risen", ["rose", "rises", "had risen"], "\"Since the new schedule began\" describes a change that started in the past and continues now, so the present perfect \"has risen\" fits."),
    ("The satellite ___ Earth every ninety minutes.", "circles", ["circled", "had circled", "will have circled"], "The sentence states a regular, ongoing fact, so the simple present \"circles\" fits."),
    ("In a few minutes, the train ___ the station.", "will leave", ["left", "has left", "had left"], "\"In a few minutes\" refers to the future, so \"will leave\" fits."),
    ("Long before humans arrived, glaciers ___ the valley into its U shape.", "had carved", ["carve", "will carve", "are carving"], "The carving was finished before another past event (humans arriving), so the past perfect \"had carved\" fits."),
    ("The chef ___ at the restaurant since it opened in 2012.", "has cooked", ["cooked", "cooks", "will cook"], "\"Since it opened in 2012\" describes work that started in the past and continues now, so \"has cooked\" fits."),
]

# (independent clause that introduces a list, list items without internal commas)
LISTS = [
    ("The recipe calls for three unusual spices", ["sumac", "smoked paprika", "dried lime"]),
    ("The camp provides everything a beginner needs", ["a tent", "a sleeping bag", "a camp stove"]),
    ("The museum's new wing is devoted to three crafts", ["pottery", "weaving", "metalwork"]),
    ("The study tracked four measures of health", ["sleep", "heart rate", "blood pressure", "daily steps"]),
    ("The trail passes three landmarks", ["a waterfall", "a fire tower", "an abandoned silver mine"]),
    ("The coach drilled the same three skills at every practice", ["passing", "footwork", "communication"]),
    ("The garden grows only native plants", ["milkweed", "coneflowers", "prairie grasses"]),
    ("The course covers three periods of history", ["the Renaissance", "the Enlightenment", "the Industrial Revolution"]),
    ("The warehouse robot performs three tasks", ["sorting packages", "scanning labels", "stacking boxes"]),
    ("The festival celebrates the region's three main crops", ["rice", "soybeans", "sweet potatoes"]),
    ("The band plays some unusual instruments", ["a washboard", "a musical saw", "a set of tuned bottles"]),
    ("The report named three causes of the delay", ["bad weather", "supply shortages", "a design error"]),
    ("The school offers three world languages", ["Spanish", "Mandarin", "Arabic"]),
    ("The volunteers collected three kinds of litter", ["plastic bottles", "fishing line", "bottle caps"]),
    ("The bakery is known for three pastries", ["croissants", "fruit tarts", "cinnamon rolls"]),
    ("The storm damaged three buildings on campus", ["the library", "the gym", "the science center"]),
    ("The novel follows three siblings", ["Mira", "Jonah", "Theo"]),
    ("The team needs to improve in three areas", ["defense", "rebounding", "free throws"]),
    ("The kit includes every part the circuit needs", ["wires", "resistors", "a small battery"]),
    ("The city plans to build three new facilities", ["a library", "a pool", "a community center"]),
    ("Honeybees collect two substances from flowers", ["nectar", "pollen"]),
    ("The exhibit displays tools from three ancient civilizations", ["Egypt", "Mesopotamia", "the Indus Valley"]),
    ("The researcher interviewed three groups of people", ["farmers", "teachers", "small-business owners"]),
    ("The magazine covers three subjects", ["science", "travel", "food"]),
    ("The park is home to several endangered animals", ["the red wolf", "the gopher tortoise", "the indigo snake"]),
    ("The new phone improves on three features", ["battery life", "camera quality", "screen brightness"]),
    ("The artist works in three materials", ["glass", "copper", "reclaimed wood"]),
    ("The survey asked about three daily habits", ["reading", "exercise", "screen time"]),
    ("The hikers packed only the essentials", ["water", "a map", "a first-aid kit"]),
    ("The factory produces three kinds of glass", ["window glass", "bottles", "lenses"]),
    ("The mural shows three moments in the town's history", ["its founding", "the arrival of the railroad", "the great fire"]),
    ("The competition has three rounds", ["a written test", "a lab practical", "an oral presentation"]),
    ("The theater needed three new things", ["curtains", "stage lights", "a sound system"]),
    ("The birds eat mainly three foods", ["seeds", "berries", "insects"]),
    ("The program teaches three coding languages", ["Python", "JavaScript", "Java"]),
    ("The river flows through three states", ["Colorado", "Utah", "Arizona"]),
    ("The menu changes with the season's produce", ["asparagus in spring", "tomatoes in summer", "squash in fall"]),
    ("The inspector checked three parts of the bridge", ["the cables", "the deck", "the support towers"]),
    ("The club meets in three places", ["the library", "the cafeteria", "the courtyard"]),
    ("The class studied three kinds of rock", ["igneous", "sedimentary", "metamorphic"]),
]

# Lists whose items contain commas, so the items are separated by semicolons.
COMPLEX_LISTS = [
    ("The tour stops in three cities", [("Lima", "Peru"), ("Accra", "Ghana"), ("Hanoi", "Vietnam")]),
    ("The panel included three experts", [("Dr. Ruiz", "a geologist"), ("Dr. Chen", "a chemist"), ("Dr. Okafor", "a climate scientist")]),
    ("The conference will meet in three cities", [("Austin", "Texas"), ("Portland", "Oregon"), ("Denver", "Colorado")]),
    ("The award went to three students", [("Maya", "a junior"), ("Leo", "a sophomore"), ("Priya", "a senior")]),
    ("The book club read three novels", [("Beloved", "by Toni Morrison"), ("Kindred", "by Octavia Butler"), ("Jazz", "also by Toni Morrison")]),
    ("The race passes through three towns", [("Millbrook", "the starting point"), ("Clearwater", "the halfway mark"), ("Stonehill", "the finish")]),
    ("The festival has three headliners", [("Nia", "a singer from Atlanta"), ("The Tides", "a surf-rock band"), ("Kwame", "a producer from Accra")]),
    ("The school hired three new teachers", [("Mr. Diaz", "who teaches physics"), ("Ms. Park", "who teaches art"), ("Mr. Hale", "who coaches track")]),
    ("The flight stops in three cities", [("Dublin", "Ireland"), ("Reykjavik", "Iceland"), ("Halifax", "Canada")]),
    ("The study compared three species", [("the red fox", "a common predator"), ("the gray fox", "a skilled climber"), ("the kit fox", "a desert dweller")]),
    ("The club has three officers", [("Ana", "the president"), ("Raj", "the treasurer"), ("Lee", "the secretary")]),
    ("The course was taught by three professors", [("Dr. Lin", "a historian"), ("Dr. Moss", "an economist"), ("Dr. Aziz", "a philosopher")]),
    ("The relay team has four runners", [("Kofi", "the fastest starter"), ("Eva", "a hurdler"), ("Sam", "a distance runner"), ("Jade", "the anchor")]),
    ("The garden has three sections", [("the herb bed", "near the gate"), ("the vegetable plot", "beside the shed"), ("the orchard", "along the back fence")]),
    ("The expedition has three stops", [("Nairobi", "Kenya"), ("Arusha", "Tanzania"), ("Kigali", "Rwanda")]),
]

# (introductory modifier, correct main clause, three dangling or misplaced versions)
MODIFIERS = [
    ("Exhausted after the long hike,", "the campers fell asleep as soon as they lay down.", ["sleep came quickly to the campers once they lay down.", "the tents were set up quickly so the campers could sleep.", "falling asleep was easy for the campers once they lay down."]),
    ("Built in 1889,", "the tower was meant to stand for only twenty years.", ["engineers meant the tower to stand for only twenty years.", "the plan was for the tower to stand for only twenty years.", "only twenty years was how long the tower was meant to stand."]),
    ("Having studied the data for months,", "the researchers finally identified the pattern.", ["the pattern was finally identified by the researchers.", "the data finally revealed a pattern to the researchers.", "a pattern finally emerged for the researchers."]),
    ("Covered in thick snow,", "the mountain pass was closed to traffic.", ["officials closed the mountain pass to traffic.", "drivers could not use the mountain pass.", "traffic was stopped at the mountain pass."]),
    ("Known for her detailed drawings of insects,", "the artist was invited to illustrate the field guide.", ["the field guide was illustrated by the artist.", "the museum invited the artist to illustrate the field guide.", "an invitation to illustrate the field guide went to the artist."]),
    ("Running late for the train,", "Malik grabbed his coffee and hurried out the door.", ["Malik's coffee was left half finished on the counter.", "the train left without Malik.", "the door slammed behind Malik as he hurried out."]),
    ("Written in just six weeks,", "the novel became a best seller.", ["the author turned the novel into a best seller.", "readers made the novel a best seller.", "sales of the novel soared."]),
    ("After tasting the soup,", "the chef added more salt.", ["more salt was added by the chef.", "the soup needed more salt.", "salt was the chef's next addition."]),
    ("Located at the edge of the desert,", "the town depends on a single underground spring.", ["residents depend on a single underground spring.", "a single underground spring supplies the town.", "water for the town comes from a single underground spring."]),
    ("Hoping to see the eclipse,", "the students climbed to the roof of the school.", ["the roof of the school was crowded with students.", "the eclipse was visible from the roof of the school.", "clouds disappointed the students on the roof."]),
    ("Carefully restored by volunteers,", "the old carousel now runs every weekend.", ["volunteers now run the old carousel every weekend.", "weekend visitors can ride the old carousel.", "rides on the old carousel are offered every weekend."]),
    ("With its bright red feathers,", "the cardinal is easy to spot in winter.", ["birdwatchers easily spot the cardinal in winter.", "spotting the cardinal in winter is easy.", "winter is a good time to spot the cardinal."]),
    ("Unlike most spiders,", "the jumping spider hunts without a web.", ["a web is not used by the jumping spider to hunt.", "hunting without a web is how the jumping spider catches prey.", "the jumping spider's hunting method does not use a web."]),
    ("As a child growing up on a farm,", "the author learned to identify dozens of birds by their songs.", ["dozens of birds were identified by the author by their songs.", "the author's knowledge of birdsong began.", "birdsong became familiar to the author."]),
    ("Trained to detect certain smells,", "the dogs can find people buried under snow.", ["people buried under snow can be found by the dogs.", "rescuers use the dogs to find people buried under snow.", "finding people buried under snow is the dogs' job."]),
    ("Nervous about her first performance,", "Lena practiced her solo one last time.", ["Lena's solo was practiced one last time.", "the solo seemed harder than ever to Lena.", "one last practice of the solo calmed Lena."]),
    ("Designed to survive strong winds,", "the new bridge sways slightly during storms.", ["engineers built the new bridge to sway slightly during storms.", "storms cause the new bridge to sway slightly.", "slight swaying is normal for the new bridge during storms."]),
    ("Originally a railway line,", "the trail now carries cyclists and walkers.", ["cyclists and walkers now use the trail.", "the town turned the trail into a path for cyclists and walkers.", "today cyclists and walkers travel along the trail."]),
    ("Frustrated by the slow internet connection,", "the students moved their study group to the library.", ["the study group was moved to the library.", "the library became the study group's new meeting place.", "the slow connection forced the study group to move."]),
    ("Grown in volcanic soil,", "the coffee has a rich, smoky flavor.", ["farmers produce coffee with a rich, smoky flavor.", "a rich, smoky flavor comes from the coffee.", "the flavor of the coffee is rich and smoky."]),
    ("Surrounded by reporters,", "the mayor answered questions for nearly an hour.", ["questions were answered by the mayor for nearly an hour.", "the press conference lasted nearly an hour.", "nearly an hour passed as the mayor answered questions."]),
    ("First discovered in 1930,", "Pluto was reclassified as a dwarf planet in 2006.", ["astronomers reclassified Pluto as a dwarf planet in 2006.", "the reclassification of Pluto happened in 2006.", "2006 was the year Pluto became a dwarf planet."]),
    ("Waiting for the bus in the rain,", "Omar wished he had brought an umbrella.", ["an umbrella would have kept Omar dry.", "the rain soaked Omar's jacket.", "Omar's umbrella was at home."]),
    ("Made entirely of recycled plastic,", "the benches in the park should last for decades.", ["the city installed benches in the park that should last for decades.", "decades of use are expected from the benches in the park.", "the park's visitors will enjoy the benches for decades."]),
    ("Determined to finish the marathon,", "the runner kept going despite a sore ankle.", ["the runner's sore ankle did not stop her.", "the finish line seemed far away to the runner.", "a sore ankle slowed the runner down."]),
    ("Found only on a few islands,", "the lizard is protected by international law.", ["international law protects the lizard.", "scientists study the lizard carefully.", "protection under international law covers the lizard."]),
    ("While walking through the market,", "we noticed a stall selling handmade kites.", ["a stall selling handmade kites caught our attention.", "handmade kites were for sale at one stall.", "the smell of fresh bread filled the air."]),
    ("Excited about the results,", "the scientists called a press conference.", ["a press conference was called by the scientists.", "the results led the scientists to call a press conference.", "the press gathered to hear the scientists."]),
    ("Painted bright yellow,", "the old farmhouse stands out against the green hills.", ["visitors notice the old farmhouse against the green hills.", "the green hills surround the old farmhouse.", "the owners made the old farmhouse stand out against the green hills."]),
    ("Unable to find a parking space,", "Dana circled the block three times.", ["the block was circled three times by Dana.", "the parking lot was full when Dana arrived.", "Dana's car circled the block three times."]),
]

# (sentence with ___, correct verb form, three wrong forms, why)
VERB_FORMS = [
    ("The ancient road, ___ by Roman engineers, still carries traffic today.", "built", ["building", "was built", "builds"], "The phrase between the commas describes the road, so it needs the past participle \"built\" (the road was built). A main verb like \"was built\" or \"builds\" can't sit inside that phrase."),
    ("The scientists ___ the samples discovered traces of an unknown mineral.", "studying", ["studied", "study", "who studying"], "The sentence's main verb is \"discovered,\" so the words before it must describe the scientists. \"Studying\" does that; \"studied\" or \"study\" would create a second main verb."),
    ("To reduce waste, the cafeteria ___ serving meals on reusable trays.", "began", ["beginning", "to begin", "having begun"], "The sentence needs a main verb for \"the cafeteria.\" Only \"began\" is a finite verb; the others leave the sentence without one."),
    ("Hikers ___ the summit before noon can see three states on a clear day.", "reaching", ["reached", "reach", "to have reached"], "The main verb is \"can see,\" so the words before it describe the hikers. \"Reaching\" does that; \"reached\" or \"reach\" would create a second main verb."),
    ("The festival, ___ every August since 1975, draws visitors from around the world.", "held", ["holding", "is held", "holds"], "The phrase between the commas describes the festival, which is held by others, so the past participle \"held\" fits. \"Is held\" and \"holds\" are main verbs."),
    ("The researchers hope ___ a vaccine within five years.", "to develop", ["developing", "developed", "develop"], "\"Hope\" is followed by an infinitive: \"hope to develop.\""),
    ("The owl, ___ its head almost all the way around, scanned the field for mice.", "turning", ["turned", "turns", "it turned"], "The phrase between the commas describes what the owl was doing as it scanned, so the present participle \"turning\" fits."),
    ("The letters ___ in the attic revealed a family secret.", "found", ["finding", "were found", "find"], "The main verb is \"revealed,\" so the words before it describe the letters. The letters were found by someone, so the past participle \"found\" fits."),
    ("___ in the Andes thousands of years ago, quinoa is now grown around the world.", "Domesticated", ["Domesticating", "It was domesticated", "Domesticates"], "The opening phrase describes quinoa, which was domesticated by people, so the past participle \"Domesticated\" fits. \"It was domesticated\" would join two sentences with only a comma."),
    ("Mia spent the afternoon ___ the fence around the garden.", "painting", ["painted", "to paint", "paints"], "\"Spent [time]\" is followed by an -ing form: \"spent the afternoon painting.\""),
    ("The museum plans ___ its hours during the summer.", "to extend", ["extending", "extended", "extends"], "\"Plans\" is followed by an infinitive: \"plans to extend.\""),
    ("The dog ___ on the porch belongs to our neighbors.", "sleeping", ["sleeps", "slept", "is sleeping"], "The main verb is \"belongs,\" so the words before it describe the dog. \"Sleeping\" does that; the other choices add a second main verb."),
    ("The mountain, ___ in clouds for most of the year, is rarely photographed from the valley.", "hidden", ["hiding", "hides", "is hidden"], "The phrase between the commas describes the mountain, which is hidden by clouds, so the past participle \"hidden\" fits."),
    ("Students ___ to join the trip must return their forms by Friday.", "wishing", ["wished", "wish", "they wish"], "The main verb is \"must return,\" so the words before it describe the students. \"Wishing\" does that without adding a second main verb."),
    ("The painting, ___ by an unknown artist, sold for a record price.", "created", ["creating", "creates", "was created"], "The phrase between the commas describes the painting, which was created by an artist, so the past participle \"created\" fits."),
    ("The old map, ___ in a library basement, shows a road that no longer exists.", "discovered", ["discovering", "discovers", "was discovered"], "The phrase between the commas describes the map, which was discovered by someone, so the past participle \"discovered\" fits."),
    ("The team celebrated after ___ its first championship in decades.", "winning", ["won", "win", "it wins"], "A preposition like \"after\" is followed by an -ing form: \"after winning.\""),
    ("The recipe requires ___ the dough overnight.", "chilling", ["chilled", "chills", "to chilling"], "\"Requires\" here is followed by an -ing form: \"requires chilling.\""),
    ("The students ___ the robot tested it in the school gym.", "who built", ["built", "build", "who building"], "The main verb is \"tested,\" so the words before it must describe the students. \"Who built the robot\" does that; \"built\" alone would create a second main verb."),
    ("The fossil, ___ to be more than 50 million years old, was found by a farmer.", "estimated", ["estimating", "estimates", "it was estimated"], "The phrase between the commas describes the fossil, which is estimated by scientists, so the past participle \"estimated\" fits."),
    ("The bakery is famous for ___ its bread in a wood-fired oven.", "baking", ["baked", "bakes", "to bake"], "A preposition like \"for\" is followed by an -ing form: \"for baking.\""),
    ("The choir, ___ by a new director this year, has doubled in size.", "led", ["leading", "leads", "is led"], "The phrase between the commas describes the choir, which is led by a director, so the past participle \"led\" fits."),
    ("The workers ___ the tunnel wore special masks.", "digging", ["dug", "dig", "were digging"], "The main verb is \"wore,\" so the words before it describe the workers. \"Digging\" does that; the other choices add a second main verb."),
    ("The town decided ___ a statue honoring its founder.", "to build", ["building", "built", "builds"], "\"Decided\" is followed by an infinitive: \"decided to build.\""),
    ("The river, ___ with snowmelt, rose nearly a meter overnight.", "swollen", ["swelling it", "swells", "was swollen"], "The phrase between the commas describes the river's condition, so the past participle \"swollen\" fits. \"Was swollen\" and \"swells\" are main verbs."),
    ("The coach asked the players ___ their phones before practice.", "to put away", ["putting away", "put away", "puts away"], "\"Asked [someone]\" is followed by an infinitive: \"asked the players to put away.\""),
]

# (noun phrase, relative word, rest of the restrictive clause, main predicate)
RESTRICTIVE = [
    ("The student", "who", "wins the essay contest", "will receive a full scholarship"),
    ("The book", "that", "you lent me last week", "is overdue at the library"),
    ("Any player", "who", "misses two practices", "must sit out the next game"),
    ("The trail", "that", "leads to the waterfall", "is closed for repairs"),
    ("People", "who", "live near the airport", "often complain about the noise"),
    ("The bridge", "that", "collapsed in the storm", "had been scheduled for repairs"),
    ("The painting", "that", "hangs above the fireplace", "was a gift from my grandmother"),
    ("Students", "who", "finish the test early", "may leave the room quietly"),
    ("The house", "where", "the author was born", "is now a small museum"),
    ("The recipe", "that", "won first prize", "uses only five ingredients"),
    ("The doctor", "who", "treated my sister", "specializes in sports injuries"),
    ("The plants", "that", "grow best in shade", "belong on the north side of the house"),
    ("The musician", "whose", "album topped the charts", "grew up in our town"),
    ("The runner", "who", "crossed the line first", "set a new state record"),
    ("The car", "that", "blocked the driveway", "was towed an hour later"),
    ("Anyone", "who", "wants a ticket", "should arrive early"),
    ("The tools", "that", "the carpenter uses most", "hang on the wall above her bench"),
    ("The company", "that", "built the stadium", "also designed the new airport"),
    ("The town", "where", "the festival began", "still hosts its final concert"),
    ("The artist", "whose", "mural covers the library wall", "will speak at the school tomorrow"),
    ("The animals", "that", "survived the drought", "moved closer to the river"),
    ("The teacher", "who", "coaches the debate team", "also teaches history"),
    ("The song", "that", "opens the album", "was recorded in a single take"),
    ("Hikers", "who", "leave the marked trail", "risk getting lost"),
    ("The engineer", "who", "designed the tunnel", "insisted on extra safety exits"),
    ("The river", "that", "flows past the school", "freezes solid most winters"),
    ("The scientist", "whose", "research changed the field", "started her career as a lab assistant"),
    ("The day", "when", "the results arrive", "will be a nervous one for the whole team"),
    ("The players", "who", "scored the most points", "were named to the all-state team"),
    ("The storm", "that", "hit the coast last week", "was the strongest in a decade"),
]
