"""Original Reading and Writing passages, part B: Information and Ideas, plus
rhetorical synthesis. Same entry format as reading_bank_a.py.
"""

MAIN = "Which choice best states the main idea of the text?"
COMPLETE = "Which choice most logically completes the text?"
NOTES = "While researching a topic, a student has taken the following notes:\n"

INFO = [
    # ---------------------------------------------------------- central ideas
    ("Central ideas and details", "medium",
     "Sea otters eat enormous numbers of sea urchins. Where otters disappeared, urchin populations exploded and grazed coastal kelp forests down to bare rock. When otters returned to parts of the Pacific coast, urchin numbers fell and the kelp regrew, bringing back the fish and invertebrates that shelter in it.",
     MAIN, "Sea otters help keep kelp forests healthy by controlling sea urchin populations.",
     ["Sea urchins are the most important animals in coastal ecosystems.",
      "Kelp forests grow back quickly after any disturbance.",
      "Fish avoid kelp forests where sea otters live."],
     "The text traces a chain: otters eat urchins, urchins eat kelp, and when otters return the kelp and the life it supports recover. The main idea is the otters' role in protecting kelp."),
    ("Central ideas and details", "hard",
     "When the printing press spread through Europe in the late 1400s, some scholars worried that cheap books would lower standards of learning, since anyone could publish anything. Yet the same flood of print let readers compare editions, spot errors, and correct them in later printings. Over time, the ability to check one text against another made printed knowledge more reliable, not less.",
     MAIN, "Although the printing press raised fears about accuracy, it ultimately helped readers improve the reliability of texts.",
     ["The printing press was invented to correct errors in handwritten books.",
      "Scholars in the 1400s refused to read printed books.",
      "Cheap books lowered standards of learning for several centuries."],
     "The text opens with a worry (lower standards), then turns (\"Yet\") to how comparing many printed copies helped fix errors, and it concludes that print became more reliable."),
    ("Central ideas and details", "medium",
     "The following text is from a short story.\n\nNadia had practiced the speech a hundred times in front of her mirror, and she knew every word. But when she stepped to the podium and saw her grandfather in the third row, wearing the tie he saved for weddings, the words slid away. She folded her notes, looked straight at him, and began to tell the story of the summer he taught her to swim.",
     MAIN, "Seeing her grandfather leads Nadia to abandon her prepared speech and speak from personal memory.",
     ["Nadia forgets her speech because she did not practice enough.",
      "Nadia's grandfather disapproves of the speech she wrote.",
      "Nadia decides not to give a speech at all."],
     "She had practiced plenty, but seeing her grandfather made her set aside her notes and tell a personal story instead."),
    ("Central ideas and details", "hard",
     "Urban trees do more than provide shade. A study of one city found that blocks with dense tree cover were up to 5 degrees Celsius cooler on summer afternoons than nearby blocks with few trees. Because heat waves are especially dangerous for older residents and people without air conditioning, the researchers argue that planting trees should be treated as a public health measure, not just a matter of appearance.",
     MAIN, "Researchers argue that urban trees provide cooling that makes them important for public health.",
     ["Trees are the most attractive feature of city neighborhoods.",
      "Older residents prefer neighborhoods without air conditioning.",
      "Heat waves have become less dangerous in cities with many trees."],
     "The text reports that trees cool city blocks and concludes that planting them should count as public health, not just appearance."),
    ("Central ideas and details", "medium",
     "Linguist Carmen Ortega studies whistled languages, in which speakers imitate the rhythm and pitch of speech with whistles that can carry for more than a kilometer. Such languages developed in mountainous regions and dense forests, where shouting was impractical. Ortega notes that as roads and phones reach these areas, fewer young people learn to whistle, and she is recording elderly speakers before the skill disappears.",
     MAIN, "A linguist is documenting whistled languages, which developed to suit rugged places and are now declining.",
     ["Whistled languages are easier to learn than spoken languages.",
      "Phones were invented to replace whistled languages.",
      "Young people in mountain regions have invented new whistled languages."],
     "The text explains what whistled languages are, why they arose, why they're fading, and Ortega's work recording them."),
    ("Central ideas and details", "hard",
     "Many people picture Antarctica as a continent where nothing lives. But beneath the ice shelves, where no sunlight reaches, scientists drilling boreholes have found fish, jellyfish, and sponges living hundreds of meters below the surface. These communities feed on bits of organic matter carried in by currents from distant open water.",
     MAIN, "Life exists in unexpected places beneath Antarctica's ice shelves, supported by food carried from elsewhere.",
     ["Antarctica is warmer beneath its ice shelves than scientists expected.",
      "Sunlight penetrates Antarctic ice shelves more than scientists assumed.",
      "Fish living beneath the ice shelves hunt jellyfish and sponges."],
     "The text corrects the idea that nothing lives in Antarctica by describing creatures under the ice shelves and how they get food without sunlight."),
    ("Central ideas and details", "medium",
     "The composer Ilse Brandt wrote most of her music for amateur choirs in small towns. Brandt believed that singing together strengthened communities, and she deliberately wrote parts that untrained singers could learn in a few rehearsals. Although she was little known in concert halls, her pieces are still sung by hundreds of community choirs.",
     MAIN, "Brandt wrote music for amateur choirs because she valued community singing, and her work remains widely performed by such groups.",
     ["Brandt was one of the most famous concert-hall composers of her time.",
      "Brandt believed that only trained singers should perform choral music.",
      "Community choirs rarely perform music written for amateurs."],
     "The text explains whom Brandt wrote for, why, and how her music lives on in community choirs."),
    ("Central ideas and details", "hard",
     "Traditional weather forecasts rely on computer models that calculate how air, water, and heat move through the atmosphere. Newer forecasting programs instead learn patterns from decades of past weather data. In recent tests, some of these programs matched the older models' accuracy for forecasts up to ten days ahead, while running in minutes instead of hours.",
     MAIN, "Forecasting programs that learn from past data have performed about as accurately as traditional models while working much faster.",
     ["Traditional weather models no longer produce accurate forecasts.",
      "Forecasts beyond ten days are now fully reliable.",
      "Weather data from past decades is too incomplete to be useful."],
     "The text contrasts two approaches and reports that the newer ones matched the older models' accuracy and ran much faster."),
    # ---------------------------------------------------------- inferences
    ("Inferences", "hard",
     "Archaeologists excavating an ancient village found hundreds of fish bones in trash pits dated to the village's early years, but almost none in pits from its later years. Over the same period, the pits show a sharp rise in the bones of sheep and goats. Meanwhile, sediment cores from a nearby lake show that it grew much shallower during the village's later years. Taken together, these findings suggest that ______",
     COMPLETE, "the villagers turned to herding as the lake became a less reliable source of fish.",
     ["the villagers stopped eating meat entirely in the later years.",
      "sheep and goats caused the lake to become shallower.",
      "the village was abandoned before the lake changed."],
     "Fish bones dropped off as the lake shrank, while sheep and goat bones rose, so the villagers likely shifted to herding as fishing declined. Nothing links the animals to the lake's change."),
    ("Inferences", "medium",
     "A company tested two versions of a sign asking hotel guests to reuse their towels. One sign said reusing towels helps the environment. The other said most guests who had stayed in that room had reused their towels. Guests who saw the second sign reused towels noticeably more often. This result suggests that ______",
     COMPLETE, "guests may be more influenced by what others have done than by an appeal to the environment.",
     ["guests do not care about protecting the environment.",
      "hotels should stop asking guests to reuse towels.",
      "guests who stay in the same room know one another."],
     "The sign about other guests' behavior worked better than the environmental appeal, pointing to the power of what others do. Saying guests don't care about the environment at all goes too far."),
    ("Inferences", "hard",
     "In a study of a songbird species, researchers found that birds living near busy highways sang at a higher pitch than birds of the same species living in quiet forests. Traffic noise is concentrated at low pitches. When the researchers played recordings of low-pitched traffic noise in a quiet forest, the birds there began singing at a higher pitch within days. These findings suggest that ______",
     COMPLETE, "the birds adjust their songs so that they can be heard over low-pitched noise.",
     ["highway birds are a different species from forest birds.",
      "the birds cannot hear low-pitched sounds.",
      "traffic noise permanently damages the birds' voices."],
     "Traffic noise is low-pitched, highway birds sing higher, and forest birds sang higher within days of hearing played-back noise. That points to a quick adjustment to be heard, not a species difference or damage."),
    ("Inferences", "medium",
     "Every book in the library's rare collection is checked out through a written request that a librarian must approve. Last month, the log of approved requests showed that three people had borrowed the 1802 atlas. Yet the atlas's own borrowing card, which every reader is required to sign, lists only two names for the month. It can be concluded that ______",
     COMPLETE, "at least one person who borrowed the atlas did not sign its borrowing card.",
     ["the librarian approved a request that was never made.",
      "the atlas was borrowed more times than the log shows.",
      "no one borrowed the atlas last month."],
     "The log shows three approved borrowers, but only two signed the card, so at least one borrower skipped signing. Nothing supports the other options."),
    ("Inferences", "hard",
     "Painter Joaquín Reyes often reused canvases, painting new works over earlier ones. X-ray images of his 1921 portrait of a dancer reveal a landscape beneath the portrait. The landscape shows a bridge that was built in 1919 and torn down in 1920. Therefore, the landscape was most likely painted ______",
     COMPLETE, "between 1919 and 1921.",
     ["before 1919.", "after the portrait was finished.", "at the same time as the portrait."],
     "The landscape shows a bridge that existed from 1919 on, so it was painted in 1919 or later, and it sits under the 1921 portrait, so it came before that. That puts it between 1919 and 1921."),
    ("Inferences", "medium",
     "A city tried to reduce litter on its beaches by installing more trash cans. Litter did not decrease. Officials then noticed that most of the litter consisted of cigarette filters and bottle caps, items that beachgoers tended to bury in the sand rather than carry to a can. This observation suggests that ______",
     COMPLETE, "adding trash cans may not address the way the most common litter ends up on the beach.",
     ["beachgoers did not use any of the new trash cans.",
      "the city should remove all trash cans from its beaches.",
      "bottle caps are more harmful than cigarette filters."],
     "The common litter was buried in the sand, not dropped for lack of a can, so more cans wouldn't solve that problem. The text doesn't say the cans went unused."),
    ("Inferences", "hard",
     "Ecologist Priya Anand compared two islands with nearly identical climates and plants. Island A has foxes, which prey on ground-nesting birds; Island B has none. Anand found that the same bird species nests on the ground on Island B but mostly in shrubs on Island A. Because the two islands differ mainly in whether foxes are present, Anand's findings suggest that ______",
     COMPLETE, "the presence of predators may influence where the birds build their nests.",
     ["the birds on Island A are a different species.",
      "shrubs grow only on Island A.",
      "foxes prefer to hunt birds that nest in shrubs."],
     "The islands match in climate and plants and differ mainly in foxes. Birds nest in shrubs only where foxes live, so predators likely shape nesting choices. The text says the plants are nearly identical, which rules out B."),
    ("Inferences", "medium",
     "The following text is from a novel.\n\nWhen the letter arrived, Theo read it standing in the doorway, then read it again sitting on the stairs. He did not call his sister, as he usually did with news. Instead he put the letter in the drawer where he kept his father's old watch and did not mention it at dinner. The text suggests that Theo ______",
     COMPLETE, "considers the letter's contents private or difficult to discuss.",
     ["has not read the letter carefully.",
      "plans to throw the letter away.",
      "is eager to share the news with his family."],
     "He breaks his habit of calling his sister, hides the letter with a treasured object, and stays silent at dinner, all of which point to news he wants to keep to himself, not news he's eager to share."),
    # ---------------------------------------------------------- command of evidence (textual)
    ("Command of evidence", "hard",
     "A student is writing about a novel in which the narrator, Ruth, runs her family's orchard after her father's death. The student claims that Ruth is uncertain about her ability to take on this role.",
     "Which quotation from the novel would most effectively illustrate the student's claim?",
     "\"Each morning Ruth walked the rows repeating her father's instructions aloud, as if afraid she might forget them, and each evening she wondered whether the trees could tell the difference.\"",
     ["\"The orchard had belonged to Ruth's family for four generations, and its oldest trees were nearly a century old.\"",
      "\"Ruth hired two workers from the village to help with the harvest that fall.\"",
      "\"Buyers from the city arrived in October, and Ruth sold every crate by noon.\""],
     "Repeating instructions \"as if afraid she might forget them\" and wondering whether the trees \"could tell the difference\" both show doubt about filling her father's role. The other quotations give facts or successes, not uncertainty."),
    ("Command of evidence", "hard",
     "Many astronomers think that some of Earth's water arrived on asteroids early in the planet's history. Planetary scientist Hana Ito argues instead that most of Earth's water was present in the rocky material from which the planet first formed.",
     "Which finding, if true, would most directly support Ito's argument?",
     "Rocks similar to the material that built the early Earth contain enough hydrogen to account for most of Earth's water.",
     ["Some asteroids that reach Earth today contain small amounts of ice.",
      "The water in Earth's oceans has changed very little in the past billion years.",
      "Comets contain a type of water that differs chemically from Earth's water."],
     "Ito claims that Earth's building material already held its water. Evidence that such rocks hold enough hydrogen to make most of that water directly supports her. The comet finding is about comets, not about Earth's building material, says nothing about the asteroid view or her own claim."),
    ("Command of evidence", "medium",
     "Nutrition researcher Diego Salas hypothesizes that students who eat breakfast at school perform better on morning tests than students who skip breakfast, because the meal improves concentration.",
     "Which finding, if true, would most directly support Salas's hypothesis?",
     "After a school began serving free breakfast, students' average scores on morning tests rose, while scores on afternoon tests did not change.",
     ["Students who ate breakfast at school reported enjoying the food.",
      "Students who skipped breakfast slept later on school days.",
      "Afternoon test scores were higher than morning scores at most schools."],
     "The hypothesis links breakfast to better morning performance. A rise in morning scores (and not afternoon scores) after breakfast began matches that timing exactly."),
    ("Command of evidence", "hard",
     "Some historians argue that a nineteenth-century canal was built mainly to carry coal to coastal cities. Historian Grace Obi contends instead that it was built mainly to carry grain from inland farms.",
     "Which finding, if true, would most directly weaken Obi's argument?",
     "Records from the canal's first ten years show that coal made up more than three-quarters of all cargo carried.",
     ["Farmers near the canal grew wheat, corn, and barley.",
      "Coastal cities imported some grain from overseas.",
      "The canal was widened twice in the twentieth century."],
     "If coal dominated the canal's cargo from the start, it's hard to argue the canal was built mainly for grain. The other findings don't compare the two cargoes."),
    ("Command of evidence", "medium",
     "Psychologist Aiko Tanaka claims that people remember information better when they explain it aloud to someone else than when they simply reread it.",
     "Which finding, if true, would most directly support Tanaka's claim?",
     "Students who explained a lesson to a classmate recalled more of it a week later than students who reread the lesson for the same amount of time.",
     ["Students preferred rereading to explaining lessons aloud.",
      "Students who explained a lesson spent more time talking than listening.",
      "Students recalled short lessons better than long ones."],
     "Only the classmate finding compares explaining with rereading, holds time equal, and measures memory, which is exactly Tanaka's claim."),
    # ---------------------------------------------------------- quantitative evidence
    ("Quantitative evidence", "medium",
     "A student compared the average daily screen time of teenagers in four countries in 2024:\nCountry P: 7.1 hours\nCountry Q: 5.4 hours\nCountry R: 8.3 hours\nCountry S: 6.0 hours\nThe student claims that teenagers in Country R spent the most time on screens of the four countries.",
     "Which choice most effectively uses data from the list to support the student's claim?",
     "Teenagers in Country R averaged 8.3 hours of screen time a day, more than in Countries P, Q, and S.",
     ["Teenagers in Country Q averaged 5.4 hours of screen time a day.",
      "Teenagers in Country P averaged more screen time than teenagers in Country S.",
      "All four countries averaged more than 5 hours of screen time a day."],
     "The claim is that R is highest. Only the answer giving 8.3 hours compares R's value with all three other countries."),
    ("Quantitative evidence", "hard",
     "A researcher recorded how many bees visited three types of flowers in a garden over one week:\nLavender: 412 visits\nSunflower: 395 visits\nMarigold: 88 visits\nThe researcher concluded that marigolds attracted far fewer bees than either of the other two flowers.",
     "Which choice most effectively uses data from the list to support the researcher's conclusion?",
     "Marigolds received 88 visits, compared with 412 for lavender and 395 for sunflowers.",
     ["Lavender received slightly more visits than sunflowers did.",
      "The three flowers received a combined total of 895 visits.",
      "Sunflowers received 395 visits over the week."],
     "The conclusion compares marigolds with both other flowers. Only the answer with all three numbers shows marigolds far behind."),
    ("Quantitative evidence", "hard",
     "A city tracked the number of riders on its bike-share program:\n2021: 48,000 rides\n2022: 61,000 rides\n2023: 59,000 rides\n2024: 83,000 rides\nA city official claims that ridership grew overall from 2021 to 2024 but did not rise every year.",
     "Which choice most effectively uses data from the list to support the official's claim?",
     "Rides rose from 48,000 in 2021 to 83,000 in 2024, although they dipped from 61,000 in 2022 to 59,000 in 2023.",
     ["Rides rose from 48,000 in 2021 to 61,000 in 2022.",
      "The highest number of rides was 83,000, in 2024.",
      "Rides fell from 61,000 in 2022 to 59,000 in 2023."],
     "The claim has two parts: overall growth and a year without a rise. The right answer covers both; the other choices give only the dip, the peak, or a single rise."),
    ("Quantitative evidence", "medium",
     "In a survey, students at a high school were asked how they usually get to school:\nWalk: 22%\nBus: 41%\nCar: 29%\nBike: 8%\nThe school's principal claims that most students do not usually travel to school by car.",
     "Which choice most effectively uses data from the survey to support the principal's claim?",
     "Only 29% of students usually travel to school by car, so the other 71% use a different method.",
     ["The bus is the most common way students travel to school.",
      "Walking is more common than biking among students.",
      "Fewer students bike to school than travel by car."],
     "\"Most students do not travel by car\" needs the car share compared with everyone else. Only 29% travel by car, which leaves 71% traveling another way."),
    ("Quantitative evidence", "hard",
     "Researchers measured the average height of seedlings grown under three types of light for four weeks:\nBlue light: 11.2 cm\nRed light: 14.8 cm\nMixed red and blue: 18.5 cm\nThe researchers concluded that combining the two colors produced taller seedlings than either color alone.",
     "Which choice most effectively uses data from the list to support the researchers' conclusion?",
     "Seedlings under mixed light averaged 18.5 cm, taller than those under red light (14.8 cm) or blue light (11.2 cm).",
     ["Seedlings under red light grew taller than those under blue light.",
      "Seedlings under blue light averaged 11.2 cm.",
      "All seedlings grew at least 11 cm in four weeks."],
     "The conclusion compares mixed light with each single color, and only the right answer gives all three values."),
]

SYNTHESIS = [
    ("Rhetorical synthesis", "medium",
     NOTES + "• The Great Wall of China is a series of walls built over many centuries.\n• Its total length, including all branches, is about 21,000 kilometers.\n• Much of the wall was built during the Ming dynasty (1368–1644).\n• Contrary to a popular myth, it is not visible to the naked eye from space.",
     "The student wants to correct a common misconception about the Great Wall. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "Although many people believe otherwise, the Great Wall of China is not visible to the naked eye from space.",
     ["The Great Wall of China is a series of walls built over many centuries.",
      "Much of the Great Wall was built during the Ming dynasty, which lasted from 1368 to 1644.",
      "Including all its branches, the Great Wall stretches about 21,000 kilometers."],
     "The goal is to correct a misconception, and only one choice mentions the myth and corrects it."),
    ("Rhetorical synthesis", "hard",
     NOTES + "• Maria Lindqvist and Tomas Berg are glassblowers.\n• Lindqvist makes large sculptures for public buildings.\n• Berg makes small drinking glasses sold in shops.\n• Both learned their craft at the same workshop in Stockholm.",
     "The student wants to emphasize a difference between the two artists' work. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "While Lindqvist creates large sculptures for public buildings, Berg makes small drinking glasses for shops.",
     ["Lindqvist and Berg both learned glassblowing at a workshop in Stockholm.",
      "Lindqvist and Berg are glassblowers.",
      "Berg makes small drinking glasses that are sold in shops."],
     "A difference needs both artists' work side by side. The right answer contrasts large public sculptures with small shop glasses; the Stockholm choice stresses what they share."),
    ("Rhetorical synthesis", "medium",
     NOTES + "• A tardigrade is an animal about half a millimeter long.\n• Tardigrades live in moss, soil, and ocean sediment.\n• They can survive being dried out for years.\n• In 2007, some tardigrades survived ten days exposed to open space.",
     "The student wants to highlight tardigrades' ability to survive extreme conditions. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "Tardigrades can survive being dried out for years, and some have even survived ten days exposed to open space.",
     ["Tardigrades, which are about half a millimeter long, live in moss and soil.",
      "Tardigrades are found in moss, soil, and ocean sediment.",
      "A tardigrade is an animal about half a millimeter long."],
     "Only the right answer gives the survival feats (drying out and space) that show how tough tardigrades are."),
    ("Rhetorical synthesis", "hard",
     NOTES + "• A community garden opened in the Eastside neighborhood in 2019.\n• It has 60 plots, all of which are rented each year.\n• A waiting list for plots has more than 120 names.\n• The city is considering whether to build a second garden.",
     "The student wants to present evidence that demand for garden plots exceeds the current supply. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "All 60 plots in the Eastside community garden are rented each year, and more than 120 people are on the waiting list.",
     ["The Eastside community garden opened in 2019.",
      "The city is considering whether to build a second community garden.",
      "The Eastside community garden has 60 plots."],
     "Demand exceeding supply needs both sides: every plot is taken, and twice as many people are still waiting. Only the right answer gives both."),
    ("Rhetorical synthesis", "medium",
     NOTES + "• The Andes are the longest continental mountain range in the world.\n• They run about 7,000 kilometers along the western edge of South America.\n• They pass through seven countries.\n• Their highest peak, Aconcagua, rises nearly 7,000 meters.",
     "The student wants to emphasize the length of the Andes. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "Running about 7,000 kilometers along South America's western edge, the Andes are the longest continental mountain range in the world.",
     ["The Andes pass through seven countries in South America.",
      "The highest peak in the Andes, Aconcagua, rises nearly 7,000 meters.",
      "The Andes are a mountain range in South America."],
     "Only the right answer gives the length (about 7,000 kilometers) and ranks it as the longest range. Aconcagua's 7,000 meters is a height, not a length."),
    ("Rhetorical synthesis", "hard",
     NOTES + "• Researcher Leila Haddad studied how long people could focus on a task.\n• Participants who took a five-minute walk every hour made 30% fewer errors.\n• Participants who stayed seated made more errors as the day went on.\n• Haddad's study involved 150 office workers.",
     "The student wants to present the study's main finding to an audience unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "In a study of 150 office workers, researcher Leila Haddad found that those who took a five-minute walk every hour made 30% fewer errors.",
     ["Haddad's study involved 150 office workers.",
      "Participants in Haddad's study who stayed seated made more errors as the day went on.",
      "Leila Haddad studied how long people could focus on a task."],
     "An unfamiliar audience needs the researcher, the study group, and the key result. Only the right answer includes all three."),
    ("Rhetorical synthesis", "medium",
     NOTES + "• Solar panels convert sunlight into electricity.\n• Wind turbines convert moving air into electricity.\n• Solar panels produce no power at night.\n• Wind turbines can produce power at any hour if the wind is blowing.",
     "The student wants to explain an advantage wind turbines can have over solar panels. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "Unlike solar panels, which produce no power at night, wind turbines can generate electricity at any hour when the wind is blowing.",
     ["Solar panels convert sunlight into electricity.",
      "Wind turbines and solar panels both produce electricity.",
      "Wind turbines convert moving air into electricity."],
     "An advantage requires a comparison. Only the right answer shows turbines working at night when panels can't."),
    ("Rhetorical synthesis", "hard",
     NOTES + "• The novel Harbor Lights was published in 1962.\n• Its author, Evelyn Park, wrote it while working as a nurse.\n• The book sold poorly at first.\n• After a film adaptation in 1985, it became a best seller.",
     "The student wants to explain how the novel's popularity changed over time. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
     "Harbor Lights sold poorly when it was published in 1962 but became a best seller after a film adaptation in 1985.",
     ["Evelyn Park wrote Harbor Lights while working as a nurse.",
      "Harbor Lights, published in 1962, was written by Evelyn Park.",
      "A film adaptation of Harbor Lights was released in 1985."],
     "A change over time needs a before and an after. The right answer gives the poor early sales and the later best-seller status, with the cause."),
]
