"""Original Reading and Writing passages, part A: Craft and Structure.

Each entry: (skill, difficulty, passage, question, correct choice, [three wrong choices], explanation).
People, studies, and stories are invented unless the fact is common knowledge.
"""

WIC = "Which choice completes the text with the most logical and precise word or phrase?"
STRUCT = "Which choice best describes the overall structure of the text?"
PURPOSE = "Which choice best states the main purpose of the text?"
FUNCTION2 = "Which choice best describes the function of the second sentence in the overall structure of the text?"

CRAFT = [
    # ---------------------------------------------------------- words in context
    ("Words in context", "medium",
     "Because the museum's new wing was built with money from hundreds of small donations rather than a single wealthy patron, the director described it as a truly ______ project, one that belonged to the whole city.",
     WIC, "communal", ["lavish", "tentative", "obscure"],
     "The wing was paid for by many ordinary donors and \"belonged to the whole city,\" so \"communal\" (shared by a community) fits. Nothing suggests it was lavish, tentative, or obscure."),
    ("Words in context", "medium",
     "Early reviewers found the composer's harmonies ______, but later listeners, accustomed to the dissonance of twentieth-century music, heard them as surprisingly gentle.",
     WIC, "jarring", ["soothing", "predictable", "elaborate"],
     "\"But\" sets up a contrast with \"surprisingly gentle,\" so early reviewers must have heard the harmonies as harsh: \"jarring.\" \"Soothing\" would agree with the later view instead of contrasting with it."),
    ("Words in context", "medium",
     "The biologist was careful not to ______ her results: although the treated plants grew faster, she noted that the trial involved only twelve plants and would need to be repeated on a larger scale.",
     WIC, "overstate", ["publish", "question", "simplify"],
     "She stresses the small sample and the need for repetition, which is how a careful scientist avoids claiming too much. \"Overstate\" means to claim more than the evidence shows."),
    ("Words in context", "medium",
     "Critics once treated the novelist's detective stories as mere entertainment, but recent scholars have argued that the books ______ serious questions about justice, class, and memory.",
     WIC, "grapple with", ["shy away from", "stumble into", "put an end to"],
     "The contrast with \"mere entertainment\" means the books engage seriously with big questions. \"Grapple with\" means to work hard at understanding. \"Shy away from\" says the opposite."),
    ("Words in context", "easy",
     "The desert tortoise is well suited to its dry habitat: it can ______ water in its bladder for months, drawing on the supply when no rain falls.",
     WIC, "store", ["waste", "detect", "share"],
     "The tortoise keeps water and draws on it later, so it must \"store\" the water."),
    ("Words in context", "hard",
     "Although the treaty was signed with great ceremony, its terms proved ______: within a year, both nations had quietly ignored the limits it set on fishing.",
     WIC, "hollow", ["binding", "generous", "intricate"],
     "The terms were ignored within a year, so they had no real force: they were \"hollow.\" \"Binding\" would mean they were enforced, the opposite of what happened."),
    ("Words in context", "medium",
     "Engineer Dana Whitlock's bridge design was praised for its ______: using only a few standard parts, it could be assembled by a small crew in less than a week.",
     WIC, "simplicity", ["grandeur", "fragility", "novelty"],
     "Being built from a few standard parts by a small crew points to \"simplicity.\" The details say nothing about grandeur or novelty, and fragility would be a flaw, not praise."),
    ("Words in context", "medium",
     "The historian's account of the strike is notably ______; she quotes factory owners and workers at equal length and lets readers weigh their claims for themselves.",
     WIC, "evenhanded", ["sentimental", "cursory", "partisan"],
     "Giving both sides equal space and letting readers judge is the definition of \"evenhanded.\" \"Partisan\" means taking one side, the opposite."),
    ("Words in context", "medium",
     "Octopuses are notoriously difficult to keep in aquariums because they are so ______: they can squeeze through any gap larger than their beak and have been known to unscrew jar lids from the inside.",
     WIC, "resourceful", ["sluggish", "timid", "predictable"],
     "Squeezing through small gaps and unscrewing lids show cleverness at solving problems, which is what \"resourceful\" means."),
    ("Words in context", "medium",
     "Rather than ______ the unpopular zoning rule, the city council chose to revise it, keeping its goal of affordable housing while removing the provisions residents objected to most.",
     WIC, "scrap", ["enforce", "celebrate", "misread"],
     "\"Rather than\" contrasts with revising the rule and keeping its goal, so the rejected option is getting rid of it entirely: \"scrap.\""),
    ("Words in context", "medium",
     "In her first album, the singer's voice sounded ______, but by her third she had learned to control its power, moving easily from a whisper to a full-throated cry.",
     WIC, "untamed", ["polished", "faint", "mechanical"],
     "The contrast with learning \"to control its power\" means her early voice was powerful but uncontrolled: \"untamed.\" \"Polished\" would make the contrast disappear."),
    ("Words in context", "easy",
     "The old map was so ______ that the archivist handled it with gloves and let no one unfold it without her supervision.",
     WIC, "fragile", ["colorful", "accurate", "common"],
     "Handling it with gloves and supervising every unfolding shows that the map could easily be damaged: \"fragile.\""),
    ("Words in context", "medium",
     "Some economists regard the rise in home gardening as a passing trend, but survey data suggest a more ______ shift: people who started gardening five years ago are still doing so at nearly the same rate.",
     WIC, "durable", ["fleeting", "expensive", "reluctant"],
     "The data show gardeners keep gardening, which contrasts with \"passing trend.\" So the shift is lasting: \"durable.\" \"Fleeting\" repeats the view the text rejects."),
    ("Words in context", "medium",
     "The coach's instructions were ______: she told each player exactly where to stand, whom to guard, and when to call for a substitution.",
     WIC, "explicit", ["vague", "optional", "hurried"],
     "Telling each player exactly what to do means the instructions were clear and detailed: \"explicit.\""),
    # ---------------------------------------------------------- text structure and purpose
    ("Text structure and purpose", "medium",
     "For centuries, sailors told stories of giant waves that rose without warning in otherwise calm seas. Scientists long dismissed these accounts as exaggerations. Then, in 1995, a sensor on an oil platform in the North Sea recorded a single wave nearly 26 meters high. Since then, satellite data have confirmed that such \"rogue waves\" are rare but real.",
     STRUCT, "It describes a long-doubted claim and then presents evidence that confirmed it.",
     ["It explains how sailors predict dangerous waves and then lists ways to avoid them.",
      "It compares two theories about ocean waves and argues that both are wrong.",
      "It describes a scientific instrument and then explains how it was invented."],
     "The text moves from sailors' stories that scientists doubted to a 1995 measurement and later satellite data that proved the stories right."),
    ("Text structure and purpose", "medium",
     "Many people assume that a painting's colors look today as they did when it was finished. But pigments change. Some reds made from insects fade in sunlight, and certain yellows darken as they react with the air. Conservators studying a painting must therefore imagine what its colors once were, a task that relies as much on chemistry as on art history.",
     PURPOSE, "To explain why the colors in old paintings may not match what the artists intended",
     ["To argue that museums should keep paintings away from sunlight",
      "To compare the value of chemistry with the value of art history",
      "To describe how insects were used to make paint"],
     "The text challenges the assumption that colors stay the same, gives examples of fading and darkening, and says conservators must reconstruct the original colors. Keeping paintings out of sunlight is a related idea, but it isn't the text's main point."),
    ("Text structure and purpose", "medium",
     "The town of Harlow once depended entirely on its textile mill. When the mill closed in 1994, nearly a third of residents lost their jobs. Rather than wait for a new factory, residents turned the empty mill into studios for artists and small businesses. Today the building houses more than sixty enterprises and employs more people than the mill did in its final years.",
     STRUCT, "It describes a setback a town faced and then explains how residents responded to it.",
     ["It traces the history of the textile industry and then predicts its future.",
      "It presents a debate among residents and then describes how it was settled.",
      "It lists the businesses in a building and then ranks them by size."],
     "The mill's closing is the setback, and converting the mill into studios is the response; the last sentence shows how that turned out."),
    ("Text structure and purpose", "medium",
     "In the following text from a short story, a woman returns to her childhood home.\n\nThe porch was smaller than Amaya remembered. She had once raced her brother from one end to the other and thought it a great distance; now she crossed it in four steps. The door still stuck in the same place, and when she shouldered it open, the house smelled, impossibly, of her mother's cinnamon bread.",
     PURPOSE, "To convey how a familiar place seems both changed and unchanged to a returning character",
     ["To explain why a character decided to sell her family's house",
      "To describe a competition between two siblings in detail",
      "To show that a character has forgotten most of her childhood"],
     "The porch feels smaller (changed), while the stuck door and the smell of bread are the same as before (unchanged). The story is about how the place strikes her now."),
    ("Text structure and purpose", "medium",
     "Honeybees perform a \"waggle dance\" to tell hivemates where to find food. The angle of the dance shows the direction of the flowers relative to the sun, and the length of the waggle shows the distance. Researchers who blocked bees from seeing the dance found that hivemates took far longer to locate food, which suggests the dance really does carry useful information.",
     FUNCTION2, "It explains how the dance conveys specific information about the location of food.",
     ["It introduces the main claim that the rest of the text disputes.",
      "It describes an experiment that tested whether the dance matters.",
      "It offers an example of a behavior unrelated to finding food."],
     "The second sentence explains what the angle and length of the dance mean, which is how the dance carries information about direction and distance. The experiment comes in the third sentence."),
    ("Text structure and purpose", "medium",
     "The first public libraries in the United States often charged small fees or limited borrowing to members. In the late 1800s, however, a movement arose to make libraries free and open to all. Supporters argued that an educated public was essential to democracy and that access to books should not depend on wealth. By 1900, free public libraries had become common in cities across the country.",
     STRUCT, "It describes an earlier practice, then a movement that changed it and the reasons behind that movement.",
     ["It presents a problem and then argues that it has never been solved.",
      "It compares libraries in two countries and then explains their differences.",
      "It describes a single library and then explains why it closed."],
     "The text moves from fee-based libraries to the free-library movement, gives the movement's reasons (democracy, equal access), and ends with its success."),
    ("Text structure and purpose", "medium",
     "Architect Rosa Ibarra designs schools with wide hallways lined with benches and whiteboards. Ibarra argues that much of students' learning happens between classes, in conversations with friends and teachers, and that buildings should make room for it. In one of her schools, teachers report that students now linger in the halls to finish solving problems they started in class.",
     PURPOSE, "To present an architect's view of how school buildings can support learning outside classrooms",
     ["To argue that schools should eliminate traditional classrooms",
      "To describe the history of school architecture",
      "To criticize teachers for letting students linger in hallways"],
     "The text explains Ibarra's reasoning (learning happens between classes) and gives an example of it working. It doesn't call for eliminating classrooms or criticize teachers."),
    ("Text structure and purpose", "medium",
     "Some astronomers expected that planets orbiting other stars would resemble those of our own solar system: small rocky planets close to the star and giant gas planets farther out. The first planets discovered around sunlike stars upended that expectation. Many were \"hot Jupiters,\" gas giants orbiting so close to their stars that a year lasts only a few days.",
     STRUCT, "It states an expectation and then describes discoveries that contradicted it.",
     ["It describes a discovery and then explains why it was later disproved.",
      "It explains how planets form and then predicts where new ones will be found.",
      "It compares two stars and then explains why one has more planets."],
     "The first sentence gives the expectation; the next two show that the first discoveries (hot Jupiters) did not fit it."),
    ("Text structure and purpose", "medium",
     "For years, the city's riverfront was lined with warehouses that blocked the public from the water. When shipping moved to a larger port downstream, the warehouses emptied. The city bought the land and replaced several buildings with a park and a bike path, and today the riverfront is one of the busiest public spaces in the city.",
     FUNCTION2, "It explains the change that made the warehouses unnecessary.",
     ["It describes the design of the new park in detail.",
      "It argues that the city should not have bought the land.",
      "It gives an example of a warehouse that is still in use."],
     "The second sentence says shipping moved and the warehouses emptied. That change opened the way for the park described in the third sentence."),
    ("Text structure and purpose", "hard",
     "The following text is from a novel.\n\nMr. Castellano measured everything. He measured the flour for his bread to the gram, the distance of his morning walk to the tenth of a mile, and the hours of his sleep to the quarter hour. So when he left the bakery one afternoon without counting his change, the shopkeeper watched him go with open alarm.",
     PURPOSE, "To establish a character's habits so that a break from them seems significant",
     ["To explain how to bake bread with precise measurements",
      "To show that the shopkeeper distrusts Mr. Castellano",
      "To describe a typical afternoon at a neighborhood bakery"],
     "The first two sentences set up how carefully he measures everything. That's why his not counting his change alarms the shopkeeper. The text builds a habit and then shows a break from it."),
    # ---------------------------------------------------------- cross-text connections
    ("Cross-text connections", "medium",
     "Text 1\nFor decades, historians described the Silk Road as a single great highway linking China and the Mediterranean, along which merchants carried goods the whole distance.\n\nText 2\nHistorian Min-jun Seo argues that this picture is misleading. Trade records show that most merchants traveled only short stretches, passing goods to others at regional markets. Seo describes the Silk Road not as a highway but as a web of overlapping local routes.",
     "Based on the texts, how would Seo (Text 2) most likely respond to the description in Text 1?",
     "By arguing that it overstates how far individual merchants traveled",
     ["By agreeing that the Silk Road connected China and the Mediterranean directly",
      "By claiming that no goods ever traveled between China and the Mediterranean",
      "By suggesting that historians have exaggerated the importance of silk"],
     "Seo says most merchants traveled only short stretches, which rejects Text 1's image of merchants carrying goods the whole way. Seo doesn't deny that goods moved across the continent, only how they moved."),
    ("Cross-text connections", "hard",
     "Text 1\nMany nutrition researchers have recommended eating breakfast every day, citing studies in which breakfast eaters weighed less on average than people who skipped the meal.\n\nText 2\nThose studies were observational: they compared people who already ate breakfast with people who didn't. In a later experiment, researchers randomly assigned adults either to eat breakfast or to skip it for sixteen weeks. Weight change did not differ between the groups.",
     "Based on the texts, how would the author of Text 2 most likely respond to the recommendation in Text 1?",
     "By suggesting that the studies behind it may not show that breakfast itself affects weight",
     ["By agreeing that everyone should eat breakfast to control weight",
      "By arguing that skipping breakfast causes weight gain",
      "By claiming that no one should eat breakfast"],
     "Text 2 points out that the earlier studies only compared existing habits, and a randomized experiment found no effect. That questions whether breakfast causes lower weight, without saying people must skip it."),
    ("Cross-text connections", "medium",
     "Text 1\nSome urban planners argue that building more roads reduces traffic congestion by giving cars more space to move.\n\nText 2\nTransportation researcher Kofi Mensah studied highway expansions in dozens of cities. He found that within a few years, traffic on widened roads typically returned to its earlier levels, because the extra space encouraged people to drive more often and farther.",
     "Based on the texts, how would Mensah (Text 2) most likely respond to the planners' argument in Text 1?",
     "He would argue that the benefit they expect tends to disappear as new driving fills the added space.",
     ["He would agree that wider roads permanently reduce congestion.",
      "He would argue that cities should close their highways entirely.",
      "He would claim that traffic congestion has no effect on drivers."],
     "Mensah found that traffic on widened roads returned to earlier levels because more driving filled the space. So the planners' expected benefit fades. He doesn't propose closing highways."),
    ("Cross-text connections", "medium",
     "Text 1\nThe poet Lin Hao is usually praised for her short, plainspoken poems about daily life, which many readers find easy to understand on first reading.\n\nText 2\nCritic Farida Noor admires Lin's poems but warns against calling them simple. Noor points out that Lin's plain words often carry double meanings, and that the poems' quiet endings frequently overturn what came before.",
     "Based on the texts, how would Noor (Text 2) most likely respond to readers described in Text 1?",
     "She would caution that the poems are more complex than they first appear.",
     ["She would agree that the poems have only one clear meaning.",
      "She would argue that Lin's poems are too difficult for most readers.",
      "She would claim that Lin's poems are not about daily life."],
     "Noor admires the poems but warns against calling them simple, because of double meanings and surprising endings. So she would say there's more to them than a first reading shows."),
    ("Cross-text connections", "medium",
     "Text 1\nEcologists have long treated wildfires in pine forests as disasters to be prevented at all costs.\n\nText 2\nForester Elena Ruiz notes that many pine species evolved alongside frequent, low-intensity fires. Such fires clear brush and let seeds sprout. Ruiz argues that decades of suppressing every fire have allowed brush to pile up, making the rare fires that do occur far more destructive.",
     "Based on the texts, how would Ruiz (Text 2) most likely view the approach described in Text 1?",
     "As a strategy that may have made severe fires more likely",
     ["As the most effective way to protect pine forests",
      "As an approach supported by the way pines evolved",
      "As irrelevant to how destructive fires become"],
     "Ruiz says suppressing every fire let brush build up, making fires more destructive. That's a criticism of Text 1's prevent-at-all-costs approach."),
    ("Cross-text connections", "medium",
     "Text 1\nSome teachers ban phones from classrooms entirely, arguing that the devices distract students from lessons.\n\nText 2\nTeacher Marcus Bell agrees that phones can distract but lets students use them for specific tasks, such as recording lab data or looking up definitions. Bell reports that setting clear rules for when phones may be used has worked better in his classes than an outright ban.",
     "Based on the texts, how would Bell (Text 2) most likely respond to the teachers in Text 1?",
     "He would share their concern but suggest that clear limits can work better than a ban.",
     ["He would reject their concern and argue that phones are never distracting.",
      "He would agree that phones should be banned from every classroom.",
      "He would argue that students should use phones throughout every lesson."],
     "Bell \"agrees that phones can distract\" but reports that clear rules worked better than a ban, so he shares the concern and proposes a different solution."),
]
